### ISSUE TITLE
Popover & Tooltip

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#1]
- [x] click trigger: click outside to close
- [x] hover trigger: keep show when hover on content
- [x] hover & focus trigger (auto trigger): use in same time [1]
- [x] event: fire a event after show/hide
- [x] auto position: always in viewport

[1]: fake code:
```coffee
$(el).on('focus blur mousein mouseout', (event)=>{
  if $(el).matches(':focus, :hover')
    $(el.tooltip).show()
  else
    $(el.tooltip).hide()
})
```

**Comment by wxsms** [comment]
> auto position: always in viewport

what is this pls? any problems or issue cases found?

**Comment by zcyzcy88** [comment]
auto decide the direction of `placement`

http://getbootstrap.com/javascript/#popovers
<img width="846" alt="2017-04-06 11_54_39-javascript bootstrap" src="https://cloud.githubusercontent.com/assets/15178410/24737264/e1841cce-1abf-11e7-9816-f9adcb53b160.png">
