### ISSUE TITLE
Collapse events not firing?

### ISSUE THREAD

**Issue by asdf072** [wxsms/uiv#101]
I'm not getting any events coming back from a collapse. Specifically, `hide` and `hidden`. Maybe I'm not listening correctly?

```
<template>
  <button @click="showCol = !showCol">Click</button>
  <collapse @hide="hideMe" v-model="showCol" tag="ul">
    <li v-for="t in things">{{ t.name }}</li>
  </collapse>
</template>
<script>
  import {Collapse} from 'uiv'
  export default {
    components: {Collapse},
    data () {
      return {
        showCol: false,
        things: [{ ... }]
      }
    },
    methods: {
      hideMe () {
        console.log("I'm hidden")
      }
    }
  }
</script>
```

Looking at the vue-devtools inspector, I don't see any events fired when I open or close.

Mac/Chrome

**Comment by wxsms** [comment]
Use the latest version.

![image](https://user-images.githubusercontent.com/5960988/32684083-3415dfca-c6bb-11e7-99b5-c0736b7a509e.png)

**Comment by asdf072** [comment]
Ugh, sorry. Working now.
