### ISSUE TITLE
I hope that create new tab by event and show the newest tab,but not work. where the problem appear？ thanks

### ISSUE THREAD

**Issue by chasenli** [wxsms/uiv#103]
### Version & browser
uiv.0.12.1 ,browser:chrome 55

### Which component
tabs

### Steps to reproduce the problem
first,thank your work. 
my trouble :
v-for in the tab component . I hope that create new tab by event and show the newest tab,but not work. 
my  code:

```
<div id="app">
  <tabs ref="refTabs">
    <tab>Tab content 1.</tab>
    <tab>Tab content 2.</tab>
   <tab v-for="t in vtabList" title="t.title">id is {{t.id}}</tab>
  </tabs>
<button @click="newTab">new tab</button>
</div>
<script>
new Vue({
	el:'#app',
	data:{
		vtab:{id:11,title:'t11'},
		vtabList:[]
	},
	methods:{
		newTab(){
			this.vtabList.push(this.vtab)
			this.nextTick(()=>{
				var len=this.$refs.refTabs.tabs.length;
				this.$refs.refTabs.select(len-1);
			})
			
		}
	}
		
})
</script>
```

**Comment by wxsms** [comment]
Hi.

Actually it is not well supported by now. I just fix this and add an working example to the doc. It will be available on next minor release.

**Comment by chasenli** [comment]
I suggest   tab component support the function of close button X,click the button close the tab. thanks.
I want to do,but my js is low.

**Comment by wxsms** [comment]
I'll see what I can do.

**Comment by wxsms** [comment]
Since the feature you suggested in not in the original bootstrap (neither css / js), I don't think it's a good idea to have this. Check out the new example code, better and closer to your idea.
