### ISSUE TITLE
Add helpers methods for opening message boxes, prompts and confirms programatically

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#105]
Having used the Element component library in the past, it would be nice if uiv would offer some helpers methods for displaying message boxes, prompts and confirms like in http://element.eleme.io/#/en-US/component/message-box. Ideally, the methods would return a promise that is rejected on cancel / dismiss and resolved on OK; in case of a prompt, with the entered user value as argument.

**Comment by wxsms** [comment]
Hi.

I'm a fans of element ui! I also love this feature. It will be implemented.

**Comment by wxsms** [comment]
ref commit: 2b787e07418ef7bebcac0a86b44e12053dc6d9df

just forgot to add issue ref while commit (not finished yet).

It will be released on next MINOR version.

**Comment by smares** [comment]
One more thing, can you add the possibility to customize the classes of the buttons? For delete prompts, I want to make the confirm button red for example by giving it the btn-danger class. :)

**Comment by wxsms** [comment]
It's done. Release comming in this weekend.
