### ISSUE TITLE
Don't use href=javascript:void(0);

### ISSUE THREAD

**Issue by beders** [wxsms/uiv#110]
### Version & browser
latest, Chrome

### Which component
Tab.vue

### Steps to reproduce the problem
Using Vue.js as part of a content script of a Chrome extension

### Expected behavior
Clicking on tabs worls

### Actual behavior
The browser reacts with:
```
Refused to execute JavaScript URL because it violates the following Content Security Policy directive: "script-src 'nonce-7KNpzGeQYX1h0reeYVinWIEtxQ0' 'strict-dynamic' 'unsafe-eval' 'unsafe-inline' https: 'report-sample'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```
While this could be worked around with, it would be much better to simply replace this with `href="#"` if possible.

That way no CSP checks are triggered.

Oh and: Thank you for making this library! Saved me a lot of time!

**Comment by wxsms** [comment]
Thanks for filling this issue, I will fix it in next patch release.

**Comment by beders** [comment]
Wow, cool. Thank you!

**Comment by beders** [comment]
Thank you!
