### ISSUE TITLE
Incorrect input behavior with Typeahead and force-select

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#114]
### Version & browser
uiv 0.13.1, Chrome 62.0.3202.94

### Which component
Typeahead

### Steps to reproduce the problem
With a Typeahead that has the force-select property set to true, even on the documentation page https://uiv.wxsm.space/typeahead/, type in something that matches the available options and select an option. After that, click into the input and select the whole text with the mouse or by pressing Ctrl+A, then type in a letter.

### Expected behavior
The letter just typed in should appear in the input

### Actual behavior
The content of the input is deleted and only the second time you press a letter, the input has it

**Comment by wxsms** [comment]
Thanks for filling this issue. Quick fix added. It was caused by #59
