### ISSUE TITLE
Incorrect tooltip position when text changes

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#115]
### Version & browser
uiv 0.13.1, Chrome 62.0.3202.94

### Which component
Tooltip

### Steps to reproduce the problem
1. Add a Tooltip and bind the text to a dynamic property
2. Set the trigger to manual and the placement to left
3. Set a short tooltip text and trigger the tooltip
4. Set a long tooltip text and trigger the tooltip

### Expected behavior
When the text changes, the tooltip should reposition itself

### Actual behavior
Depending on the length of the previous text, the tooltip is misplaced

**Comment by smares** [comment]
Here's a quick pen: https://codepen.io/anon/pen/RjQgeX

**Comment by wxsms** [comment]
You can fix this by wrapping `this.tooltipVisible = true;` into a `$nextTick` function temporarily.

https://codepen.io/wxsm/pen/RjQvyQ

**Comment by smares** [comment]
I tried this already but it doesn't really fix the problem. It's especially visible if you have several buttons next to each other that change the text and trigger the tooltip visibility on hover and you quickly move the mouse over them. I will post a pen once I am in the office. I also tried setting the fade duration to 0 but it didn't solve the issue.

**Comment by smares** [comment]
Sorry, got sick and didn't make it to the office. 👎 

Here's an updated pen demonstrating my problem more precisely.

**Comment by wxsms** [comment]
Fixed now. There might be same issue with popover, will check later.

**Comment by wxsms** [comment]
You can remove the `$nextTick` call and try with you pen again, as I see it is working as expect now.

**Comment by schmidtk** [comment]
@wxsms It looks like the popover fix does not work when using the popover slot. Would it be possible to reposition when the slot content changes or somehow notify the popover to reposition?

**Comment by schmidtk** [comment]
As a workaround I added `:content="content"` to the popover, initialized `content` as an empty string, then when my popover slot content changes:

```
this.content = ' ';

this.$nextTick(() => {
  this.content = '';
});
```

This will trigger a `resetPosition` call in the popover but still display my slotted content.
