### ISSUE TITLE
please exemple dropdown not-close-elements

### ISSUE THREAD

**Issue by nlefebvre1410** [wxsms/uiv#118]
Hello,
Could you give me an example of using dropdown not-close-elements because I have trouble visualizing this method

**Comment by wxsms** [comment]
Simply pass an array of HTML element.

`Typeahead.vue` is using it:

https://github.com/wxsms/uiv/blob/master/src/components/typeahead/Typeahead.vue

**Comment by nlefebvre1410** [comment]
hi,
I wish to make a list as in the picture
Thank you in advance for your assistance

![sans titre](https://user-images.githubusercontent.com/3309884/33238980-d2cca6c4-d298-11e7-8732-c7f427c1cda8.png)

```html
<dropdown ref="dropdown" :not-close-elements="[{value:'a',value:'a'}]">        
<btn type="primary" class="dropdown-toggle">Filter type<span class="caret"></span></btn>
                    <template slot="dropdown">
                        <li>
                            <input type="checkbox" id="a" value="a">
                            <label for="a">All publications's type</label>
                        </li>
                        <li>
                            <input type="checkbox" id="b" value="b">
                            <label for="b">Edute diverse</label>
                        </li>
                        <button class="btn btn-primary">Apply</button>
                    </template>
                </dropdown>`

**Comment by wxsms** [comment]
@nlefebvre1410 https://codepen.io/wxsm/pen/vWaJvP

**Comment by nlefebvre1410** [comment]
a big thank-you

**Comment by wxsms** [comment]
Welcome. Feel free to star this repo if you found it helpful.
