### ISSUE TITLE
TimePicker can scroll / click the arrow to change number, when readonly [bug]

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#12]

**Comment by zcyzcy88** [comment]
click the arrow also cause value changed.
please fix it.

**Comment by wxsms** [comment]
Read-only-input is for the input box, not for the component.

**Comment by zcyzcy88** [comment]
OK,
But it is confusing.

**Comment by wxsms** [comment]
any advise?

**Comment by zcyzcy88** [comment]
When `readonly`, value should cannot be changed by arrow or input or scroll.
Completely `readonly` instead of `readonly-input`.
