### ISSUE TITLE
Can't change tab children class

### ISSUE THREAD

**Issue by renandiett** [wxsms/uiv#124]
### Version & browser
v0.14.2

### Which component
Tabs, Tab

### Expected behavior
I need to change the `<ul>` class from Tabs component

### Actual behavior
Can't change the `<ul>` class attribute from Tabs component

**Comment by wxsms** [comment]
You don't have to add class to `ul` inside tabs in most cases. For example, if you want to change some styles -> #43 

If this is not what you're looking for, pls show me your case, thanks.

**Comment by wxsms** [comment]
closing due to no response.
