### ISSUE TITLE
Support bottom offset for affix

### ISSUE THREAD

**Issue by anowell** [wxsms/uiv#125]
I'm looking for a way to set a bottom offset for an affix commponent - a point at which affix will stop being affixed. I'll probably be sitting down to grok how bootstrap is doing this in the coming days and may submit a UIV PR, but if it's something you're deeply familiar with and can easily implement, or have specific guidance with respect to what might be accepted as a PR, I'm all ears.

**Comment by wxsms** [comment]
Hi,

Thank you for being interested in this project. I don't know that there is such `bottom` offset in Bootstrap Affix, but looks like a good idea, PR is always welcome 👍

**Comment by wxsms** [comment]
Closing due to not active for a long time.
