### ISSUE TITLE
Issue with overflow-y: scroll, modals and padding-right

### ISSUE THREAD

**Issue by arrancardnell** [wxsms/uiv#127]
### Version & browser
uiv@0.14.3

Browser
Firefox: 57.0
Chrome: 62.0.3202.94

### Which component
Modal

### Steps to reproduce the problem

```
body {
    overflow-y: scroll;
}
```

```
<template>
  <section>
    <btn type="primary" @click="open1=true">Large Modal</btn>
    <modal v-model="open1" title="Modal Title" size="lg">
      <p>This is a large modal.</p>
    </modal>
  </section>
</template>
<script>
  export default {
    data () {
      return {
        open1: false,
      }
    }
  }
</script>
```

I'm currently using `overflow-y: scroll` on `body` to display a scrollbar on every page, even those that don't require scrolling. The same issue appears to occur when using `overflow-y: scroll` on `html` as well.

### Expected behavior

In plain Bootstrap 3, `padding-right` is applied to the `body` and the scrollbar is removed, even if the scrollbar is purely visual and the page cannot be scrolled.

### Actual behavior

Opening a `modal` on page that doesn't extend beyond the scroll height (i.e. the scrollbar is visible on the page but has no scroll to drag) does not apply any `padding-right `to the `body` when using `overflow-y: scroll`, which causes page jumping. The `padding-right` only seems to be applied if the scrollbar becomes active/valid, so if you open the browser console and extend the height of the `body` to beyond the height of the window, the padding will be applied when opening the modal.

**Comment by wxsms** [comment]
Thank you for filling this issue. it will be fixed in next release.
