### ISSUE TITLE
Feature request: Add custom class to $alert, $confirm and $prompt

### ISSUE THREAD

**Issue by ouzman** [wxsms/uiv#129]
I am trying to use $alert like [bootstrap3-dialog](https://github.com/nakupanda/bootstrap3-dialog)  with message types but I cannot add any custom class to modals. A new parameter will be perfect for my case.

**Comment by wxsms** [comment]
Thanks for the PR. Pls read my notes in it.

**Comment by wxsms** [comment]
will be released on this weekend.
