### ISSUE TITLE
Image handling for Carousel component?

### ISSUE THREAD

**Issue by TBiddy** [wxsms/uiv#131]
I love UIV, thank you for making it!

I'm having trouble figuring out how to handle images within the Carousel, and I didn't see any explanation for how to go about it.

I was using the original Bootstrap 3 configuration and attempted to stack files in a similar fashion.

The **first image** will display in the carousel, but any following images **won't**.
 
Here's my current code:
<code>
```
<uiv-carousel>
    <uiv-slide v-for="(slide, index) in slides" :key="index">
      <img v-for="(slide, index) in slides" :key="index" v-bind:src="slide.poster">
      <div style="width: 100%;height: 500px;" :style="{background:index % 2 === 0 ? '#99a9bf' : '#d3dce6'}"></div>
      <div class="carousel-caption">
        <h3>{{slide.title}}</h3>
        <p>
          <router-link :to="{ name: 'mypage' }" class="btn btn-lg btn-blue" role="button">
            <i class="fas fa-play" aria-hidden="true"></i> Watch
          </router-link>
        </p>
      </div>
    </uiv-slide>
    <template slot="indicators" slot-scope="props">
      <ol class="carousel-indicators custom-carousel-indicators">
        <li v-for="(slide, index) in slides"
            :class="{active:index === props.activeIndex}"
            @click="props.select(index)">
        </li>
      </ol>
    </template>
  </uiv-carousel>

<script>
  export default {
    data () {
      return {
        slides: [
          {title: 'Title1', poster: 'https://sample_image1.png'},
          {title: 'Title2', poster: 'https://sample_image2.png'},
          {title: 'Title3', poster: 'https://sample_image3.png'}
        ]
      }
    },
    methods: {
      pushSlide () {
        this.slides.push({title: `Slide ${this.slides.length + 1}`})
      }
    }
  }
</script>
```
</code>
How should image files be placed to make them move through the carousel?

Thanks!

**Comment by wxsms** [comment]
https://codepen.io/wxsm/pen/GyRawa

**Comment by TBiddy** [comment]
Thank you!

Unfortunately, this is still not working for me. No images will pass through the display in the example nor from my own files.

Everything works fine except for the images.

If it helps, I am using Vue templates (for an SPA) and using this as an individual Vue component within another page. Ex: `<video-carousel></video-carousel>` on `VideoPage.vue`.

**Comment by wxsms** [comment]
The pen does not work for you? What browser you're using?

**Comment by TBiddy** [comment]
I am using Chrome. But it doesn't work in Firefox or Safari either.

**Comment by wxsms** [comment]
I just opened it in my Safari on iPhone and it works... You need to wait for the images to load.

**Comment by TBiddy** [comment]
Yes. It will work independently on CodePen, but I can't get it to work within my app in a Vue template nor with my own files.

Images just won't display. Anyway, thanks for your help. I can't figure out what the issue is.

**Comment by wxsms** [comment]
You don't need a `v-for` in `<img>`.

**Comment by wxsms** [comment]
And the div with background color can be removed. It's just for demo.

**Comment by TBiddy** [comment]
> You don't need a v-for in <img>.

That's it! Works now.

THANK YOU!

**Comment by wxsms** [comment]
welcome.
