### ISSUE TITLE
Closing modal re-enables body scrollbar even though other modals are visible

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#133]
### Version & browser
uiv 0.14.5, Chrome 63.0.3239.108

### Which component
Modal / MessageBox

### Steps to reproduce the problem
1. Create a page that is long enough for a vertical scrollbar to appear
2. Open a modal -> the modal hides the body scrollbar and you cannot scroll the body which is good
3. From within that modal, trigger a message box that itself is a second modal -> the body scrollbar is still hidden and you cannot scroll, good
4. Dismiss the message box leaving the modal from step 2 open -> suddenly, the body scrollbar appears and the body is scrollable even though a modal is still visible, bad 😢 

### Expected behavior
Only closing the last modal should re-enable the body scrollbar

### Actual behavior
Once you close any modal, the body scrollbar appears again no matter if other modals are still visible

**Comment by smares** [comment]
One more thing: While the backdrops stack (I see that with multiple modals, the underlying body is getting darker and darker), I think that the backdrop of the second modal should cover the first modal and so on.

**Comment by wxsms** [comment]
Thank you for filling this issue.

Nested modals are not supported by now (MessageBox too). I'll consider this as an enhancement.

**Comment by smares** [comment]
I see, thanks for the quick feedback. Would love to see this added! 😃
