### ISSUE TITLE
Add support for async data in Typeahead that comes from a store

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#134]
The Typeahead component currently supports setting data either as `data` property or `async-src` where it performs an AJAX call itself. It would be nice however to be able to supply the data asynchronously using a callback method like Element handles this in their Select component: http://element.eleme.io/#/en-US/component/select#remote-search This way, one can implement their own method for querying a remote server either via AJAX POST request, WebSocket, whatsoever.

Also, is there currently a way to have Typeahead use a plain key/value object with the keys being set to the v-model and the values being the displayed labels? Currently it seems that I can only use objects of the form `{ data: 'foo', label: 'bar' }` and I can only set the label using the `item-key` property, but the v-model will get the whole object as value.

**Comment by wxsms** [comment]
Query function is a good point.

As for the key/value object data, it is not possible for now. However I don't think that this is necessary to be handled inside the lib once we have the query function implemented...

I think that, in most cases user will expect the model to be an object while using Typeahead. If you want something else inside it, you can use a computed value to do so. But I can add some prop like `item-value` to make it easier.

**Comment by smares** [comment]
I have currently implemented my own async loading by callback using a v-model for the input that I am watching and inside the watch I am mutating the `data` that I pass to the Typeahead component. What I noticed though is that while my data mutates instantly, the dropdown of the typeahead shows the options only on second key press. I will make a fiddle / pen to demonstrate.

**Comment by smares** [comment]
Here you go: https://codepen.io/anon/pen/KZzWYX

If you start typing "Germany", notice how the dropdown appears only after "Ge". Am I doing something wrong?

**Comment by smares** [comment]
I see there is no watch on the `data` property internally in the component which might be the reason why I see this. The dropdown appears to be filled with options only when the value of the input changes and since the data is fetched asynchronously, there might be some race conditions.

**Comment by wxsms** [comment]
> I see there is no watch on the data property internally in the component which might be the reason why I see this.

Yes. and it is how the Typeahead designed to work with **local data**, which does not mean to be changed on every type. You will need the new async function for custom async query (coming soon).

Btw, sadly, I found that prop like `item-value` is not possible for now, for some reason, there will be a big change to take... but you can also easily achive this with computed value base on the `v-model` that bind to Typeahead.
