### ISSUE TITLE
UI is distorted with datepicker, showing header variables

### ISSUE THREAD

**Issue by deepHackMode** [wxsms/uiv#137]
### Actual behavior
<img width="899" alt="screen shot 2017-12-20 at 2 30 24 pm" src="https://user-images.githubusercontent.com/12871318/34199119-ab82476a-e592-11e7-99f4-ff23e2bbb7bf.png">

Kindly help.

**Comment by wxsms** [comment]
seems your language pack is not loading correctly.

if you're using `vue-i18n`, make sure to have language pack merged corretlly -> https://uiv.wxsm.space/i18n#with-vue-i18n

**Comment by smares** [comment]
vue-i18n 7.3.3 is causing problems on my end, modals throw an error `Error in render: "TypeError: Cannot read property '_t' of undefined"` Maybe it's related.

**Comment by wxsms** [comment]
@deepHackMode If you're also using 7.3.3 of vue-i18n -> #138

**Comment by deepHackMode** [comment]
@wxsms - Thanks much! language merge was the problem I guess. I'll look into it.
I'm using vue-i18n version 7.3.2

**Comment by wxsms** [comment]
@deepHackMode welcome. closing now. feel free to continue here if that was not your problem.

**Comment by l0rda** [comment]
Hi @wxsms 

same problem for me with latest uiv(0.26.2).
If not using vue-i18n smallest width of datepicker modal window is 516px.
Same if not using locale at all.

If using vue-i18n( version 8.1.0) i got same error:
```TypeError undefined is not an object (evaluating 'i18n._t')```

Tested in Safari 12 and Firefox 62

**Comment by wxsms** [comment]
@l0rda Sry, I can't repro your problem. can you try to create a simplest reproduce? thanks.

btw, template address: https://codepen.io/wxsm/pen/VMGRwG if you needed.
