### ISSUE TITLE
Cannot read property '_t' of undefined with modals and vue-i18n 7.3.3

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#138]
### Version & browser
uiv 0.15.0, vue-i18n 7.3.3, Chrome 63.0.3239.108

### Which component
Modals and MessageBox

### Steps to reproduce the problem
Include a Modal or MessageBox component on the page

### Expected behavior
No errors

### Actual behavior
"Cannot read property '_t' of undefined" is thrown with vue-i18n 7.3.3. It works fine with vue-i18n 7.3.2.

**Comment by wxsms** [comment]
I just created an issue to vue-i18n: https://github.com/kazupon/vue-i18n/issues/264

pls use 7.3.2 for now, before I found any solution from there.

**Comment by wxsms** [comment]
0.15.1 fixed this.

**Comment by sumeshkmp** [comment]
Getting Cannot read property '_t' of undefined in vue-i18n v7.4.2.

Version
Vue - 2.9.3
Nuxt - 1.3.0

**Comment by l0rda** [comment]
TypeError: undefined is not an object (evaluating 'i18n._t')

uiv 0.26.2
vue-i18n 8.1.0
