### ISSUE TITLE
No body padding added when modal opens with body's overflow-y: scroll and no scrolling is required

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#140]
### Version & browser
uiv 0.15.1, Chrome 63.0.3239.108

### Which component
Modal and MessageBox

### Steps to reproduce the problem
Create a short page and set the body `overflow-y` to `scroll` so that a scrollbar is always present no matter if the body has to be scrolled or not. **However, pay attention that the page does not require scrolling for this test and only displays a disabled vertical scrollbar.** If the page has to scroll, everything works as intended.

Open a modal / message box.

### Expected behavior
The body scrollbar is removed and a right padding is added to compensate for the hidden disabled scrollbar.

### Actual behavior
The body scrollbar is removed and no padding is added. This causes elements on the page with 100% width to shift slightly to the right.

**Comment by wxsms** [comment]
This is fixed in #127 

Do not add `overflow-y: scroll` directly to inline styles, because that will override the styles in class `modal-open`. You can do this in your css file:

```css
body {
  overflow-y: scroll;
}
```

And it will work as your expect (tested).

**Comment by wxsms** [comment]
Sry. my bad. it was a problem since last update...

**Comment by wxsms** [comment]
fixed in 0.15.2

**Comment by smares** [comment]
The bug is back in 0.15.5. Reverting to 0.15.4 until this is fixed.

**Comment by ouzman** [comment]
I think `modal-open` class should be added to body when modal shown. Otherwise, long modal content cannot be scrolled on a short page. @smares

**Comment by wxsms** [comment]
@smares You may use `overflow-y: scroll` in a way that can override `modal-open`. such as inline style or `!important`. then it should be find.
