### ISSUE TITLE
jsx Dropdown component, problem slot rendering

### ISSUE THREAD

**Issue by mymtw** [wxsms/uiv#142]
### Version & browser
latest

### Which component
Dropdown

### Steps to reproduce the problem
I added jsx in `.babelrc` as `  "plugins": ["transform-vue-jsx", "transform-runtime"]`
then doing next:
```
<ul class="nav navbar-nav navbar-right">
  <Dropdown tag="li">
    <a class="dropdown-toggle" role="button">Dropdown 3<span class="caret"></span></a>
    <div slot="dropdown">
      <li><a role="button">Action</a></li>
      <li><a role="button">Another action</a></li>
      <li><a role="button">Something else here</a></li>
      <li role="separator" class="divider"></li>
      <li><a role="button">Separated link</a></li>
    </div>
  </Dropdown>
</ul>
```
### Expected behavior

```
<ul class="nav navbar-nav navbar-right">
<li class="dropdown open">
  <a role="button" class="dropdown-toggle">
    Dropdown 3<span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
      <li><a role="button">Action</a></li>
      <li><a role="button">Another action</a></li>
      <li><a role="button">Something else here</a></li>
      <li role="separator" class="divider"></li>
      <li><a role="button">Separated link</a></li>
  </ul>
</li>
</ul>
```

### Actual behavior
```
<ul class="nav navbar-nav navbar-right">
<li class="dropdown open">
  <a role="button" class="dropdown-toggle">
    Dropdown 3<span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <div> <<<--------THIS DIV IS EXPLICIT
      <li><a role="button">Action</a></li>
      <li><a role="button">Another action</a></li>
      <li><a role="button">Something else here</a></li>
      <li role="separator" class="divider"></li>
      <li><a role="button">Separated link</a></li>
    </div>  <<<--------THIS DIV IS EXPLICIT
  </ul>
</li>
</ul>
```

**Comment by wxsms** [comment]
Just follow the document.

`<div slot="dropdown">` is incorrect. you should use `<template slot="dropdown">`

**Comment by mymtw** [comment]
@wxsms template it's vue construct, I'm afraid that jsx should not use template

**Comment by wxsms** [comment]
Em... I see. but I'm not good at JSX of Vue.js

* does `<template>` work in JSX? If yes, then there should be no problem.
* If it doesn't work, then I don't think that there is something I can help you with. It should be a usage problem of [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx), like 'how to use template tag in JSX'

Because the only way to render a slot content without a parent tag like `<div>` is using `<template>`.

**Comment by mymtw** [comment]
yes `<template>` construct works, I simply thought, that there exists a way to render slot without parent div.
