### ISSUE TITLE
strange bundle size

### ISSUE THREAD

**Issue by mymtw** [wxsms/uiv#143]
### Version & browser
latest

### Which component
Dropdown, Collapse, Alert
### Steps to reproduce the problem
```
import { Dropdown, Collapse, Alert } from 'uiv'
export default {
  name: 'mycomponent',
  components: { Dropdown, Collapse, Alert },
  render () {
    return (
     <div>
        <Collapse class="navbar-collapse" value={this.showNavbar}>
                <ul class="nav navbar-nav navbar-right">
                  <Dropdown tag="li">
                    <a class="dropdown-toggle" role="button">
                      {this.current_user.name}{' '}
                      <span class="caret"></span>
                    </a>
                    <template slot="dropdown">
                      <li role="separator" class="divider"></li>
                      <li><a role="button">Exit</a></li>
                    </template>
                  </Dropdown>
                </ul>
        </<Collapse>
        <Alert dismissible onDismissed={this.handleDismissed} id="topAlert" type={this.alertOptions.atype}>
          {this.someError}
       </Alert>
      </div>
    )
  }
}
```
### Expected behavior
I expected that size of my bundle with imported uiv will be smaller in case vendor.9f180d8b00b3467ba3d4.js.

### Actual behavior
I imported 3 components `import { Dropdown, Collapse, Alert } from 'uiv'`
(here all builds without gzipping as you can see)

**this is my minified build for prod environment, without importing 3 components**
vendor.a0939b59cce5c5e0a4ec.js   **162 kB**       0  [emitted]  vendor
app.a0939b59cce5c5e0a4ec.js  10.4 kB       1  [emitted]  app

**this is my minified build for prod environment, with imported 3 components**
vendor.9f180d8b00b3467ba3d4.js   **229 kB**       0  [emitted]  vendor
app.9f180d8b00b3467ba3d4.js  10.6 kB       1  [emitted]  app

Is it really ok, import 3 components = `+ 67kb` to bundle size?

**Comment by wxsms** [comment]
> Is it really ok, import 3 components = + 67kb to bundle size?

No. This seems to be a full lib size.

This is actually a bundler's job. For example, if you're using Webpack: https://webpack.js.org/guides/tree-shaking/

The lib itself will serve ESM bundle for you if your bundler supports ES6 import/export, which allows tree shaking.

**Comment by mymtw** [comment]
@wxsms hm...I'm using webpack, completely cloned repo from here https://github.com/vuejs/vue-hackernews-2.0
and everything that I added it - jsx.
Maybe you're wrongly exporting your components?

**Comment by wxsms** [comment]
Maybe you can try lodash in your project, for example:

```javascript
import {findIndex} from 'lodash'
```

And see if you're getting the full lib size.

**Comment by mymtw** [comment]
looks like yes, full lib size, now he is 301kB:
```
  vendor.143d003f1726ef5aa507.js   **301 kB**       0  [emitted]  [big]  vendor
     app.143d003f1726ef5aa507.js  13.5 kB       1  [emitted]         app
manifest.143d003f1726ef5aa507.js  1.38 kB       2  [emitted]         manifest
 common.143d003f1726ef5aa507.css   109 kB       1  [emitted]         app
    vue-ssr-client-manifest.json  3.89 kB          [emitted]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets:
  vendor.143d003f1726ef5aa507.js (301 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (300 kB). This can impact web performance.
Entrypoints:
  app (425 kB)
      manifest.143d003f1726ef5aa507.js
      vendor.143d003f1726ef5aa507.js
      app.143d003f1726ef5aa507.js
      common.143d003f1726ef5aa507.css


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

**Comment by mymtw** [comment]
I found how to import lodash correctly:
https://github.com/webpack/webpack/issues/2867#issuecomment-342094767
if Im importing like in those comment => I'm getting 249kb:
```
                           Asset     Size  Chunks             Chunk Names
  vendor.a676416c7b7fa32ca5e4.js   249 kB       0  [emitted]  vendor
     app.a676416c7b7fa32ca5e4.js  13.5 kB       1  [emitted]  app
```

**Comment by wxsms** [comment]
Yes.. I'm actually using lodash like that currently. 😞 

Anyway, I don't think this is an issue of the lib, apparently Webpack is not doing the tree shaking job as expect.

**Comment by mymtw** [comment]
but maybe it is possible to allow to import component like in `lodash` (`import throttle from 
'lodash/throttle'`)

instead of:
`import { Alert } from 'uiv'`
to 
`import Alert from 'uiv/components/alert'`
?

**Comment by wxsms** [comment]
Yes. you may try:

```javascript
import Alert from 'uiv/src/components/alert/Alert.vue'
```

But remember to turn on Babel transform for this lib.

**Comment by mymtw** [comment]
no. did not work
```
ERROR in vendor.14c2a9ffaa6792a53e45.js from UglifyJs
Unexpected token: name (width) [vendor.14c2a9ffaa6792a53e45.js:12883,6]

ERROR in vendor.14c2a9ffaa6792a53e45.js from UglifyJs
Unexpected token: name (width) [vendor.14c2a9ffaa6792a53e45.js:12883,6]
```
ok

**Comment by WulfP** [comment]
2 Years later it still seems not to be possible to reduce bundle size.
> 150k is to much for 2 or 3 components.

Are there still no plans to make it possible to import only single components?

**Comment by wxsms** [comment]
@WulfP Just added a new way to do this:

```js
import Alert from 'uiv/dist/Alert'
```

try in 0.35.1

**Comment by WulfP** [comment]
@wxsms This ist cool! Thanks for your quick reply. Works perfect!

In your "Getting startet / Import individually" example you mention both ways but not the huge difference between them. Besides that, unfortuantely the recommended way ist commented out.

VSCode reports:

`import Modal from 'uiv/dist/Modal' 10.8K (gzipped: 4K) `

but

`import { Modal } from 'uiv' 159.4K (gzipped: 47K)`

A short notice about how to import modules selectively and prefixed could be helpful too:

`Vue.component('uiv-modal', Modal)`

before

`new Vue(...)`

or

`new Vue({components: {'uiv-modal': Modal})`

**Comment by wxsms** [comment]
@WulfP Thanks for your advice. But I may be busy these days. If you have any idea to improve the docs, pls feel free to create PR.
