### ISSUE TITLE
Width of justified tabs

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#144]
Hello! I am not sure if this is a bug or intended behavior:

### Version & browser
uiv 0.15.4, Chrome 63.0.3239.108

### Which component
Tabs

### Steps to reproduce the problem
Add the Tabs component with some tabs and set its `justified` property to `true`

### Expected behavior
Tabs should have the same width, so 2 tabs should each have 50% of the available width, 3 tabs should each have 33% of the available width, etc.

### Actual behavior
The tabs have different widths.

**Comment by wxsms** [comment]
can you provide any demos or screen shots?

**Comment by smares** [comment]
https://codepen.io/anon/pen/rpGNeO

In my case, even though I have the exact same two tabs and titles, the first one is wider than the second one.

**Comment by wxsms** [comment]
It should be a Bootstrap style issue, not related to this lib. check this out: https://getbootstrap.com/docs/3.3/components/#nav-justified

The tabs are also with different widths.

**Comment by smares** [comment]
You are right. The fix is setting `.nav-justified` to `display: table; table-layout: fixed;` and `.nav-tabs.nav-justified > li` to `width: 100%;`

**Comment by smares** [comment]
Meh, my fix breaks IE. The first tab has full width and the remaining tabs are squeezed.
