### ISSUE TITLE
Modal component scroll-y problem

### ISSUE THREAD

**Issue by oliverkan** [wxsms/uiv#145]
### Version & browser
version: 0.15.4 - browser: chrome- Version 63.0.3239.132 (Official Build) (64-bit)

### Which component
Modal

### Steps to reproduce the problem
When you Add modal component into a page that has smaller height than modal height and than after opening modal you can't scroll down. But if when I want to open modal in a page that has already y axis scroll, also modal has scroll too. If neccessary I can add screenshot of problem.

### Expected behavior
Modal component should have scrool-y according to the window size responsively.

**Comment by oliverkan** [comment]
I'm adding two screeshots, first one is inspect of when scroll bar is not visible. second one is inspect of when scroll bar is visible.
<img width="1438" alt="screen shot 2018-01-08 at 00 02 26" src="https://user-images.githubusercontent.com/4508745/34654157-a9ca30ca-f408-11e7-8e72-374ba7f977f5.png">
<img width="1436" alt="screen shot 2018-01-08 at 00 03 04" src="https://user-images.githubusercontent.com/4508745/34654160-b0d7706c-f408-11e7-9927-06b7787278f5.png">

**Comment by wxsms** [comment]
Fixed in 0.15.5. Thanks for PR from @ouzman

**Comment by smares** [comment]
The changes broke #140 again.

**Comment by wxsms** [comment]
@smares Fixed in 0.15.6, see https://codepen.io/wxsm/pen/KyxVOg
