### ISSUE TITLE
Sometimes tooltips are "enterable", sometimes not

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#147]
### Version & browser
uiv 0.15.6, Chrome 63.0.3239.132

### Which component
Tooltip

### Steps to reproduce the problem
1. Add a tooltip component on a page and place a button inside or any other element that triggers the tooltip on hover
2. Hover the button
3. Slowly or quickly move the mouse inside the tooltip

### Expected behavior
The tooltip should either always hide when the mouse leaves the button even if the mouse cursor is inside the tooltip, or the tooltip should always be "enterable" meaning that if the mouse is inside the tooltip, the tooltip remains visible.

The best thing would be having an option to control this such as Element UI's `enterable` property. (http://element.eleme.io/#/en-US/component/tooltip#attributes)

### Actual behavior
Sometimes the tooltip disappears when the mouse leaves the button and approaches the tooltip, sometimes it stays visible and I can freely move the mouse inside the tooltip without it disappearing.

**Comment by wxsms** [comment]
It is 'enterable' now. I think that the `enterable` prop of Element is making the tooltip not disapear immediately, but with a little timeout.

**Comment by smares** [comment]
Any chance you can make the enterable optional? 😁 In my case, I would like the tooltip to disappear as soon as I leave its activator. I am using it in a table with checkboxes where some checkboxes show a tooltip. As you can imagine, having the tooltips enterable can slow down the process if you have to click on many checkboxes.

Just checked Element and as soon as you set `enterable` to false, the tooltip disappears if you leave the activator even when you move the cursor into the tooltip.

**Comment by wxsms** [comment]
Yes, I will do this.
