### ISSUE TITLE
[TimePicker] add option in props in order to hide arrows

### ISSUE THREAD

**Issue by francoismassart** [wxsms/uiv#151]
### Version & browser
0.16.0

### Which component
`TimePicker`

### Proposition
I'd like to add a prop `hideControls` which has a `default` value of `false`.

If this prop is set to `true` then the UP and DOWN controls will be hidden in order to reduce the height of the component...

Let me know if you agree with this proposal, if so, I will make the changes inside a PR via a dedicated branche.

**Comment by wxsms** [comment]
Thanks for the proposal. PR is welcome.

However, I'd like to change the prop name to `controls` and default value to `true`, which will be more consist with the lib.

**Comment by francoismassart** [comment]
Should my PR use `dev` as destination branch ?

**Comment by wxsms** [comment]
Yes, please.
