### ISSUE TITLE
[TimePicker] Allow the use of the `up` & `down` keys to increase/decrease hours and minutes

### ISSUE THREAD

**Issue by francoismassart** [wxsms/uiv#152]
### Version & browser
0.16.0

### Which component
`TimePicker`

### Proposition
When the focus is set in the hours or the minutes fields, I'd like to add the possibility of using the `up` and `down` arrow keys to increase/decrease the time.

Let me know if you agree with this proposal, if so, I will make the changes inside a PR via a dedicated branche.

**Comment by wxsms** [comment]
It looks like that this is a bug after setting v-model to lazy. I will fix this one.
