### ISSUE TITLE
Vertical tabs

### ISSUE THREAD

**Issue by ultrasamad** [wxsms/uiv#154]
How do I implement vertical tabs with the tab component, where the tabs lie vertically either on the right or left and the content on the other side.

Thanks.

**Comment by wxsms** [comment]
Hi. There're no **vertical tabs** in Bootstrap 3. You might need https://getbootstrap.com/docs/3.3/components/#nav-pills

**Comment by ultrasamad** [comment]
@wxsms Ok. thanks. With the horizontal tabs, how do I add scrollable feature so that overflow tabs will not stack  but rather have a scrollable behaviour.
Any help on that?
Thanks.

**Comment by wxsms** [comment]
https://stackoverflow.com/questions/22582520/bootstrap-horizontal-scrollable-tab-bar
