### ISSUE TITLE
Allow set initial offset for notification

### ISSUE THREAD

**Issue by StephenPCG** [wxsms/uiv#156]
### Version & browser
`^0.16.1`

### Which component
`Notification`

### Steps to reproduce the problem
If there is a top nav bar, notification overlaps with nav bar.

The position is hard coded in generated code:

```
style="position: fixed; top: 15px; width: 300px; transition: all 0.3s ease-in-out; right: 15px;"
```

If there is a top nav bar, the first notification overlaps with the nav bar. It will be better if it allows to set an initial offset on registering the notification service. Or maybe another approach, allow the caller to provide a container instead of body for the notification.

**Comment by wxsms** [comment]
It's done, pls use v0.17.0

**Comment by StephenPCG** [comment]
Thanks a lot!

**Comment by wxsms** [comment]
the deploy to npm is in progress, wait a minute...

**Comment by StephenPCG** [comment]
Can you write a config interface to set `offsetY` just once? Something like:

```js
import * as uiv from 'uiv'
uiv.configNotification({offsetY: 50})
```

So that I only need to set it once and globally, rather then add `offsetY: 50` to each `$notify()` call.

BTW, before this change, I figured out a workaround. I added a custom class to each call:

```js
this.$notify({..., customClass: 'uiv-notification'})
```

And add the following global css:

```css
.uiv-notification {
  margin-top: 50px!important;
}
```

This works well, but I have to remember to add the custom class to each `$notify` call. Maybe you can add a default class to all notifications, and allow users to customize just via css.

**Comment by StephenPCG** [comment]
Wow, works like a charm!
