### ISSUE TITLE
Should auto build & deploy to GitHub Pages

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#16]
https://docs.travis-ci.com/user/deployment/pages/
https://docs.travis-ci.com/user/deployment/npm/

<br>

---

<br>

And edit meta:
<img width="858" alt="2017-04-12 01_14_46-zcyzcy88_selfcolle_ a repository just for myself" src="https://cloud.githubusercontent.com/assets/15178410/24921612/01af31ac-1f1e-11e7-8cee-f31ca6731876.png">

<br><br>

**Comment by wxsms** [comment]
Very useful suggestion. Done now. Thanks!
