### ISSUE TITLE
Tabs Transition

### ISSUE THREAD

**Issue by isometriq** [wxsms/uiv#160]
I just updated the package and found out that there is a transition when tabs change.

Although it is nice, I don't want this transition across the board. Is there a way I could disable it globally somehow ?

**Comment by wxsms** [comment]
There'no global config for this. you can use `<tabs :transition-duration="0">`

**Comment by isometriq** [comment]
ok, yes I know that
I was hoping for a way to not having to specify a 0 duration everywhere

**Comment by wxsms** [comment]
You can achieve this by extending the default Tabs.vue component. something like:

```javascript
var CustomTabs = {
  extends: Tabs,
  props: {
      transitionDuration: {
        type: Number,
        default: 0
      }
}
```
