### ISSUE TITLE
Tooltip Directives not working [SOLVED]

### ISSUE THREAD

**Issue by MoraesGil** [wxsms/uiv#161]
Hi i follow step by step of setup installation and uiv working with tags
` <tooltip text="Static tooltip content goes here" trigger="manual" v-model="show">
      <btn>You Can't Trigger Tooltip Here...</btn>
    </tooltip>`

but not working this way as i need

`<btn v-tooltip="'Static tooltip content goes here'" type="primary">Hover me!</btn>`

maybe some config is missing can help me?

**Comment by wxsms** [comment]
You may try to intall uiv with prefix.

**Comment by MoraesGil** [comment]
i already use since the first installation
import * as uiv from 'uiv'
Vue.use(uiv, {prefix: 'uiv'}) 

i try find another solution because appears

**Comment by wxsms** [comment]
`v-uiv-tooltip`, the v prefix is enforce by vue.

**Comment by MoraesGil** [comment]
main.js
 
```
//global config
import * as uiv from 'uiv'
Vue.use(uiv, {prefix: 'uiv'})
```
 
teste.blade.php 
```
<div id="app">
     <tooltip text="Static tooltip content goes here" trigger="hover" >
      <label>THIS WORKING</label>
    </tooltip>
    <br>
    <label v-uiv-tooltip="'sssda tooltip content goes here'" trigger="hover">THIS NOT WORK</label>
  </div>
  <script src="js/main.js"></script>

  <script type="text/javascript">
  $( document ).ready(function() {
    new Vue({
      el:'#app', 
      data(){
        return {
         
        }
      }, 
    })
  });
</script> 
```
same error
`[Vue warn]: Failed to resolve directive: uiv-tooltip`

**Comment by wxsms** [comment]
Could you pls provide a reproduce example link, like jsFiddle / codepen? I could not reproduce this problem.

**Comment by MoraesGil** [comment]
I solve the problem with  my npm was installing v ^0.11.11

i put ^0 and run npm install them last version 0.18 was installed successfully 

now everything is working great
