### ISSUE TITLE
Impossible to reset TimePicker at runtime

### ISSUE THREAD

**Issue by francoismassart** [wxsms/uiv#162]
### Version
v0.18.0

### Which component
TimePicker

### Steps to reproduce the problem
Once the TimePicker has been mounted, set the `v-model` prop value to an invalid date like `new Date('')`

### Expected behavior
The hours and minutes input fields should be empty and show their placeholders

### Actual behavior
The hours and minutes inputs not empty, they are showing `00` as value

### Notes
I already made the fix for this issue, I'll make a PR for a branch `date-picker-reset-at-runtime` with 2 commits:

- First commit will add a test in the spec file, so you can test the issue
- Second commit will fix the issue inside the TimePicker component

**Comment by wxsms** [comment]
Thanks!
