### ISSUE TITLE
typeahead click handlers not working

### ISSUE THREAD

**Issue by jomofrodo** [wxsms/uiv#164]
### Version & browser
0.18  Chrome/FF

### Which component
Typeahead

### Steps to reproduce the problem
Include typeahead component in a page

### Expected behavior
When UL list expanded, mouse click will make a selection

### Actual behavior
Selection only happening with CR

**Comment by wxsms** [comment]
Hi there. What do you mean CR pls? I can select items by clicking in document examples. Could you pls provide a reproduce link?

**Comment by jomofrodo** [comment]
Hi, sorry:  CR = Carriage Return.
I will try to set up an example of what I am seeing in a gist.

**Comment by jomofrodo** [comment]
So I created a jsFiddle, just using the stock code from the documentation:
https://jsfiddle.net/jomofrodo/wzmwqsow/1/

This code runs on jsFiddle. But on my server, my local dev server running on tomcat, it does not! Any thoughts?

**Comment by jomofrodo** [comment]
Based on the above finding, I went and checked.  The script is working fine on all other environments: SIT/UAT/Production.  So, clearly something in my dev environment.  I can't figure out what, though!

Anyway, thanks for creating a very nice library.  Feel free to close this.

**Comment by jomofrodo** [comment]
Actually I found the problem. Was only present in code on my dev server. I had added a <script> block above the opening <html> tag on my page.  This was causing problems with click handling in the Typeahead object.  I don't know why.  I moved the misplaced <script> block to the footer and all problems are gone.

**Comment by wxsms** [comment]
Thank you. Closing.
