### ISSUE TITLE
Datepicker: Option to provide custom highlighting

### ISSUE THREAD

**Issue by asiamov** [wxsms/uiv#166]
Currently only "today" can be highlighted in the Datepicker component in addition to the selected date.

It would be nice if there was support for providing a callback function for setting the button classes.
That way you could invidually set a custom class for every button/date for example for coloring fully booked dates red, bookable dates green etc.

**Comment by smares** [comment]
The solution with the array is less flexible than a callback. Imagine one wants to give a special color to all weekends or to all mondays (let's say you're a restaurant and monday is your day off). You would have to create a large array with all those weekends or mondays.

**Comment by wxsms** [comment]
@smares I see. any (detail) suggestions on how to implement this better? or existing solutions?

**Comment by smares** [comment]
I think the way Element does this for disabled dates is running each date (day) of the currently displayed month against a callback function. That callback could return a string / array holding the classname(s) to apply to the days.

**Comment by asiamov** [comment]
I was initially thinking of something like this:
https://jsfiddle.net/6yspsuyx/
