### ISSUE TITLE
Bootstrap 4 suuport

### ISSUE THREAD

**Issue by ianfoulds** [wxsms/uiv#170]
Just wondering if you are planning to support Bootstrap V4 soon. I've just started with Vue and currently have a few projects I am migrating that are on Bootstrap 3, but I will be migrating to B4 eventually. I am looking for Vue components that use B3 and are actively moving to B4.

Many thanks.
Ian.

**Comment by smares** [comment]
https://github.com/wxsms/uiv/issues/157

**Comment by wxsms** [comment]
maybe I should keep that one open. closing.
