### ISSUE TITLE
Generating dynamic accordion.

### ISSUE THREAD

**Issue by ultrasamad** [wxsms/uiv#171]
I am not quite sure how to use this in generating dynamic accordions.
So I generated these dynamic accordions but run into a situation where by, when I click the first accordion all others opened and subsequent clicks does nothing. 

`<div class="panel-group" v-for="(val, key) in payload" :key="key">
            <div class="panel panel-default">
                <div class="panel-heading" role="button"  @click="toggleAccordion(key)">
                    <h4 class="panel-title">{{ key }}</h4>
                </div>
                <collapse v-model="showAccordion[0]">
                    <div class="panel-body" style="color:black;">
                        {{ val }}
                    </div>
                </collapse>
            </div>
        </div>`

`data() {
        return {
            showAccordion: [true, false, false]
        }
    },
    methods: {
        toggleAccordion (index) {
            if (this.showAccordion[index]) {
            this.$set(this.showAccordion, index, false)
            } else {
            this.showAccordion = this.showAccordion.map((v, i) => i === index)
            }
      }
    }`

I basically picked the example in the docs but this time trying to generate them dynamically.
Actually I'm not sure if I need to update the `showAccordion` array.

**Comment by wxsms** [comment]
This is a Vue.js question and have nothing to do with this lib. Pls try search with Google or ask in some place like StackOverflow, thanks!

**Comment by ultrasamad** [comment]
Oh ok. Thanks @wxsms
