### ISSUE TITLE
Modal loses focus after closing a MessageBox on it

### ISSUE THREAD

**Issue by MyHeartsECO** [wxsms/uiv#172]
### Version & browser

0.19.0
Chrome Version 64.0.3282.167 

### Which component

Modal, MessageBox

### Steps to reproduce the problem

1. Open a modal
2. Display a messageBox on it
3. Close the messageBox

### Expected behavior

Body should have `modal-open` class.

### Actual behavior

Modal loses the focus (body loses `modal-open` class).

**Comment by MyHeartsECO** [comment]
https://github.com/wxsms/uiv/issues/167 is related.

**Comment by wxsms** [comment]
Can you provide a reproduce?

This works without any problem in my env:

```html
<template>
  <section>
    <btn type="primary" @click="open1=true">Open set of nested modals</btn>
    <modal v-model="open1" title="Modal 1" size="lg">
      <p>This is a simple large modal.</p>
      <p>Click on the button below to open a nested modal.</p>
      <btn type="info" @click="openMsgBox">Open Modal 2</btn>
    </modal>
  </section>
</template>
<script>
  export default {
    data () {
      return {
        open1: false
      }
    },
    methods: {
      openMsgBox () {
        this.$alert({
          title: 'Title',
          content: 'This is an alert message.'
        })
      }
    }
  }
</script>
<!-- modal-nested.vue -->
```

**Comment by MyHeartsECO** [comment]
@wxsms I've just realized we were using it wrong. We can close this issue. Thanks!
