### ISSUE TITLE
"disabled" prop on dropdown not respected

### ISSUE THREAD

**Issue by markgajdosik** [wxsms/uiv#173]
### Version & browser
0.19.0 (latest)

### Which component
dropdown

### Steps to reproduce the problem
1. Create dropdown with `:disabled="true"`

### Expected behavior
The dropdown button is disabled.

### Actual behavior
The dropdown button isn't disabled and its possible to click on the dropdown.

Thanks!

**Comment by wxsms** [comment]
the prop `disabled` in dropdown is not mean to disable the button, but disable the dropdown menu from opening. if you want the btn to be disabled, simply add `disabled` to the btn itself.

**Comment by markgajdosik** [comment]
Hi wxsms, I figured, thanks. I can see that having `disabled` prop controlling `disabled` on the btn component in the dropdown's default slot is not straightforward. Feel free to mark as closed and thanks for having a look at the ticket.
