### ISSUE TITLE
Missing local registration in multi-select component

### ISSUE THREAD

**Issue by felixtruong69** [wxsms/uiv#174]
Vue Documention: https://vuejs.org/v2/guide/components.html#Local-Registration
### Version & browser
0.19.0

### Which component
multi-select

### Steps to reproduce the problem
`
Vue.use(uiv, { prefix: 'uiv' });
`
### Expected behavior
No error

### Actual behavior
[Vue warn]: Unknown custom element: \<dropdown\> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

_Sorry for my bad English_

**Comment by wxsms** [comment]
Thanks for filling this issue. I will publish a patch version to fix this soon.
