### ISSUE TITLE
Radio buttons are not updating reactive data

### ISSUE THREAD

**Issue by isometriq** [wxsms/uiv#176]
### Version & browser
Vue: 2.5.13
UIV: 0.18.0
Chrome: 64.0.3282.186

### Which component
Btn / BtnGroup

### Steps to reproduce the problem
Test A:
```
<btn-group>
    <btn input-type="radio" input-value="1" v-model="profile">None</btn>
    <btn input-type="radio" input-value="2" v-model="profile">Use Existing</btn>
    <btn input-type="radio" input-value="3" v-model="profile">Create New</btn>
</btn-group>
```
Test B:
```
<btn input-type="radio" input-value="1" v-model="profile">None</btn>
<btn input-type="radio" input-value="2" v-model="profile">Use Existing</btn>
<btn input-type="radio" input-value="3" v-model="profile">Create New</btn>
```
Data is declared in host component
```
data: ()=>({
    profile: '1'
})
```

### Expected behavior
With Test A, `this.profile` value is updated when pressing on the buttons, as it reactive and bound with the `v-model`.

### Actual behavior
With Test A, `this.profile` is NOT updated. And the first "radio" is NOT selected (as value is "1").
With Test B,  `this.profile` is updated (but the layout is scrambled without the enclosing `<btn-group>`).

**Comment by isometriq** [comment]
Btw, the `<template>` in the examples in the docs are not valid because there is not single root element. If I'm right, that should go in another issue.

**Comment by isometriq** [comment]
The same happens with `input-type="checkbox"`

**Comment by isometriq** [comment]
The radio or checkbox ui is working (toggles as expected, it's just the model that is not updated. Another thing I noted is that it initializes correctly with the model data. So if data is set to `profile:  '2'` , the correct element is selected. But does not changes after when interacting.

**Comment by isometriq** [comment]
With breakpoints on `node_modules/uiv/src/components/button/Btn.js`, I see that the  `change` event is not triggered, when the `Btn` is enclosed in an `BtnGroup` and does when alone.
```
          on: {
            change () { // <---- does not trigger
              if (props.inputType === INPUT_TYPE_CHECKBOX) {
                if (isInputActive) {
                  props.value.splice(props.value.indexOf(props.inputValue), 1)
                } else {
                  props.value.push(props.inputValue)
                }
              } else {'COUCOU', console.log(props.inputValue);
                listeners['input'](props.inputValue)
              }
            }
          }
```

**Comment by isometriq** [comment]
This does not work as well:
```
<div data-toggle="buttons" class="btn-group">
    <btn input-type="radio" input-value="1" v-model="profile">None</btn>
    <btn input-type="radio" input-value="2" v-model="profile">Use Existing</btn>
    <btn input-type="radio" input-value="3" v-model="profile">Create New</btn>
</div>
```
But this does...
```
<div class="btn-group">
    <btn input-type="radio" input-value="1" v-model="profile">None</btn>
    <btn input-type="radio" input-value="2" v-model="profile">Use Existing</btn>
    <btn input-type="radio" input-value="3" v-model="profile">Create New</btn>
</div>
```
..so I fear I have some side-effects from bootstrap javascript file! It should not be there, but maybe I'm wrong, so I'll verify that.

**Comment by isometriq** [comment]
Dammit, found this `require('bootstrap-sass');`... probably for nav dropdowns that were there before. I'll use UIV components for that and get rid of that dependency!
...all ok now ..my baaad

**Comment by moplin** [comment]
@isometriq I am having this problem, I can reproduce your exact behavior, but I don't understand the solution.

**Comment by isometriq** [comment]
If I recall, the `require('bootstrap-sass');` statement introduce the necessary javascript to use the bootstrap components and this was interfering with UIV. Removing it allows UIV to manipulate the elements as intended.

**Comment by moplin** [comment]
Cant find it, 'require('bootstrap-sass');', I don't have this on my project. Cant make them work

**Comment by isometriq** [comment]
It's possible that was something I added in the past ..I'm pretty sure it was included in the Laravel project. where I had the issue. Try to see if there is another library or script that should not be there or that is interfering...
