### ISSUE TITLE
Tooltips without white space overflow background

### ISSUE THREAD

**Issue by smares** [wxsms/uiv#179]
### Version & browser
0.19.1 in Chrome 64.0.3282.186

### Which component
Tooltips

### Steps to reproduce the problem
Add a tooltip with a long text without white space

https://codepen.io/anon/pen/paMXEP (hover the red asterisk)

### Expected behavior
Tooltip should be as long as the text

### Actual behavior
Tooltip background is cut, but the text overflows it

**Comment by wxsms** [comment]
this is actually a css problem. you can fix this by adding:

```css
.tooltip-inner {
  max-width: unset !important;
}
```

**Comment by smares** [comment]
Ah, I see it's from Bootstrap itself and since I am using `bootstrap-scss` it is controllable via `$tooltip-max-width`. 👍
