### ISSUE TITLE
newbie seeking help CSS & Import { }  from 'uiv'

### ISSUE THREAD

**Issue by danialhr** [wxsms/uiv#18]
I tried updating to v0.11.1 but CSS seems to still not work.

Appreciate advise on what I did wrong.

` <template>
 <div style="background-color: #fff; width: 100vw; height: 100vh;">

      <dropdown v-model="open">
          <button @click="open = !open" class="btn btn-default dropdown-toggle" type="button">
            <span>Dropdown</span>
            <span class="caret"></span>
          </button>
          <template slot="dropdown">
            <li><a role="button">Action</a></li>
            <li><a role="button">Another action</a></li>
            <li><a role="button">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a role="button">Separated link</a></li>
          </template>
        </dropdown>
      </div>

  </div>
</template>

<script src="path/to/vue.min.js"></script>
<script src="path/to/uiv.min.js"></script>

<script>
import Parallax from 'vue-parallaxy'
import VideoBg from 'vue-videobg'
import { Dropdown } from 'uiv'

export default {
  name: 'hello',
  components: {
     Parallax,
     VideoBg,
     Dropdown
   },
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>
`
<img width="450" alt="screen shot 2017-04-14 at 10 36 34 am" src="https://cloud.githubusercontent.com/assets/7851981/25031443/85d60b1c-20ff-11e7-823e-8617f1586d82.png">
<img width="660" alt="screen shot 2017-04-14 at 10 36 51 am" src="https://cloud.githubusercontent.com/assets/7851981/25031444/860cc058-20ff-11e7-921a-9b2f026a4f49.png">

**Comment by wxsms** [comment]
1. You don't need to do `<script src="path/to/vue.min.js"></script> <script src="path/to/uiv.min.js"></script>` if you're using vue-loader, these are for browser users (not using webpack ect.)
2. You should add `open: false` to your data. then it should work.

**Comment by zcyzcy88** [comment]
1. delete code of `<script src="path/to/vue.min.js"></script>`
2. edit `package.json`, make version `^0.11`
```json
"dependencies": {
  ...
    "uiv": "^0.11",
  ...
},
```
3. run `npm update`

#17
