### ISSUE TITLE
DatePicker limit-from doesn't limit date correctly

### ISSUE THREAD

**Issue by Mandy27** [wxsms/uiv#187]
### For Example:
`<date-picker v-model="startDate" format="MM/dd/yyyy" :limit-from="2018-3-15"/>`

I am still able to pick March 14

**Comment by wxsms** [comment]
can't see this problem. pls provide a reproduce link.

if you're looking for a template: https://codepen.io/wxsm/pen/VMGRwG

**Comment by Mandy27** [comment]
Here is the issue that I am encoutering
https://codepen.io/athenablue27/pen/zWBoxz

**Comment by wxsms** [comment]
It still not happen to me... can you provide your timezone?

**Comment by Mandy27** [comment]
Pacific Time
