### ISSUE TITLE
The body will shake where Modal component show  in IE11

### ISSUE THREAD

**Issue by hetianqi** [wxsms/uiv#188]
Version & browser
0.19.1 & IE 11

Which component
Modal

Steps to reproduce the problem
1. body has vertical scrollbar
2. modal don't have vertical scrollbar
3. show the modal

Expected behavior
1. hide the body's scrollbar
2. the body will not shake

Actual behavior
the body will shake

**Comment by hetianqi** [comment]
[https://github.com/hetianqi/images/blob/master/uiv-modal-shaking-bug.gif?raw=true](url)

**Comment by hetianqi** [comment]
![uiv-modal-shaking-bug.gif](https://github.com/hetianqi/images/blob/master/uiv-modal-shaking-bug.gif?raw=true)

**Comment by wxsms** [comment]
thanks for the feedback. fixed now.
