### ISSUE TITLE
Event API design

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#19]
### present tense
name-style like native DOM event

- [x] alert
- [x] pagination
- [x] tabs

---

### no prefix
custom event won't bubble

- [x] modal
- [x] pagination
- [x] popover
- [x] tooltip

---

#### `change` event
- [x] carousel
- [x] pagination
- [x] tabs

better with [semantic `v-modal`](https://vuejs.org/v2/guide/components.html#Customizing-Component-v-model)

**Comment by wxsms** [comment]
present tense & no prefix
Pls provide some detail.

**Comment by zcyzcy88** [comment]
`changed` -> `change`
`popover-show` -> `show`
