### ISSUE TITLE
javascript error when opening modal

### ISSUE THREAD

**Issue by StevenSongToronto** [wxsms/uiv#195]
### Version & browser
IE11 & Chrome

### Which component
modal

### Steps to reproduce the problem
1. use webpack to include uiv.esm.js
2. copy the first modal sample into a test page
3. click button "Launch Demo Modal"
4. javascript error shows at line 2487 saying "TypeError: Cannot read property 'contain' of undefined.
5. it is caused by this.$refs.pop being undefined.
![err](https://user-images.githubusercontent.com/23745676/38109494-4aa2897e-3366-11e8-8c47-fed32e68ba32.PNG)

**Comment by wxsms** [comment]
does this happen in original document examples?

**Comment by StevenSongToronto** [comment]
https://uiv.wxsm.space/modal 
is ok. I tested with the simple html using .min.js without issue.
I am using typescript,  vue-class-component, vue-property-decorator, vue-router, vuex, vuelidate.
Where is "popup" defined in <template> like ref="popup"? I could not find it.
By checking source, I could not find how the popup mixin is used by modal.vue.

**Comment by wxsms** [comment]
> Where is "popup" defined in like ref="popup"? I could not find it.

It is in popover & tooltips. Because the first modal has those inside it.

**Comment by wxsms** [comment]
Can't reproduce this.

**Comment by StevenSongToronto** [comment]
I found the following facts:
1. The error only happens with v-popover directive like 
     <v-busy />
     <btn v-popover="{content:'Popover without a title'}" type="primary">Popover</btn>
2. When I removed my <v-busy /> component, error disappeared.
    In VueBusy script, I subscribed rxjs Subject in created() method like
    created() {
      mySvc.busySource.subscribe(() => ....)
    }
3. When I put <v-busy /> after <btn v-popover....>, error disappeared.
4. I still put <v-busy /> ahead of <btn v-popover...>, and changed created() to mounted(), then error disappeared.

Therefore, the error has been solved. But I still hope you can give me some insights.
Thanks a lot.
