### ISSUE TITLE
Issues using Typeahead when displaying the results.

### ISSUE THREAD

**Issue by 1quintana** [wxsms/uiv#196]
I am using VUE.js v2.5.15, UIV 0.19.1 and bootstrap 4.0.0-beta.3. The browser is chrome  62.0.3202.75 

I just installed the library, but I am having some Issues using the Typeahead when displaying the results.

I do not have errors and I can see the results coming with not problem, but is not displaying the dropdown to click on the selection,

Here is the code and I am attaching an image where you can see that the results are there, but I needed to remove to style display:none from the class dropdown-menu.

I would appreciate any help with this issue.

```
<template>
    <section>
        <label for="input-4">Users of Github:</label>
        <input id="input-4" class="form-control" type="text" placeholder="Type to search...">
        <Typeahead v-model="model" target="#input-4" async-src="https://api.github.com/search/users?q=" async-key="items" item-key="login"/>
        <br/>
        <!--<alert v-show="model">You selected {{model}}</alert>-->
    </section>
</template>
```

<pre>
<script>
    import {Typeahead} from 'uiv'

    export default {
        components: {Typeahead},
        data () {
            return {
                model: '',
            }
        }
    }
</script>
</pre>

![screenshot from 2018-03-30 11-09-25](https://user-images.githubusercontent.com/11234646/38142867-0fb2265c-340c-11e8-91fc-3f3778cc406e.png)

**Comment by wxsms** [comment]
This lib is for Bootstrap 3.
