### ISSUE TITLE
recommended add form common components

### ISSUE THREAD

**Issue by pengpan** [wxsms/uiv#200]
### Version & browser Vue.2.4

Recommended to add radio checkbox switch and other common components.
Because bootstrap native  components are ugly, I hope the author can beautify them.

**Comment by wxsms** [comment]
Hi. thanks for the suggestion.

This lib isn't intend to make Bootstrap looks better, but to migrate the functionalities from jQuery version to Vue.

If you need better styles, you can simply use CSS: https://stackoverflow.com/questions/44279398/customize-bootstrap-checkboxes
