### ISSUE TITLE
$attrs is readonly / $listeners is readonly when displaying notifications

### ISSUE THREAD

**Issue by markgajdosik** [wxsms/uiv#201]
### Version & browser
Chromium Version 65.0.3325.181 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)
Firefox 59.0.2 (64-bit)

### Which component
N/A (Notifications)

### Steps to reproduce the problem
Use `this.$notify()` to display a notification, e.g.:
```js
this.$notify('This is a simple notify msg.', () => {
    console.log('dismissed')
})
```

### Expected behavior
Notification appears without a warning in the browser console.

### Actual behavior
Notification appears with the below warning in the browser console:

```
[Vue warn]: $attrs is readonly.

found in

---> <Alert>
       <Root>
       
warn	@	vue.esm.js:591
(anonymous)	@	vue.esm.js:4501
reactiveSetter	@	vue.esm.js:1006
updateChildComponent	@	vue.runtime.esm.js:2834
prepatch	@	vue.runtime.esm.js:4140
patchVnode	@	vue.runtime.esm.js:5921
patch	@	vue.runtime.esm.js:6092
Vue._update	@	vue.runtime.esm.js:2666
updateComponent	@	vue.runtime.esm.js:2784
get	@	vue.runtime.esm.js:3138
run	@	vue.runtime.esm.js:3215
flushSchedulerQueue	@	vue.runtime.esm.js:2977
(anonymous)	@	vue.runtime.esm.js:1833
flushCallbacks	@	vue.runtime.esm.js:1754
Promise.then (async)		
microTimerFunc	@	vue.runtime.esm.js:1802
nextTick	@	vue.runtime.esm.js:1846
Vue.$nextTick	@	vue.runtime.esm.js:4513
mounted	@	uiv.esm.js:4287
callHook	@	vue.runtime.esm.js:2917
mountComponent	@	vue.runtime.esm.js:2798
Migrater.../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount	@	vue.runtime.esm.js:7995
init	@	uiv.esm.js:4376
(anonymous)	@	uiv.esm.js:4397
notify	@	uiv.esm.js:4396
open_target_field_modal	@	m-field-mapper-grid.vue:350
invoker	@	vue.esm.js:2027
Vue.$emit	@	vue.esm.js:2538
map	@	m-field-mapper-field-map.vue:53
invoker	@	vue.esm.js:2027
Vue.$emit	@	vue.esm.js:2538
map	@	m-field-mapper-field-map-entry.vue:78
invoker	@	vue.esm.js:2023
fn._withTask.fn._withTask	@	vue.esm.js:1826
```
I don't get this warning in the docs (https://uiv.wxsm.space/notification).

**Comment by wxsms** [comment]
are you using browserify as packager?

**Comment by wxsms** [comment]
see #119 if related or not

**Comment by markgajdosik** [comment]
I am seeing this with webpack	4.5.0 + vue-loader 14.2.2. I will have a look at #119 but I don't think we're ready to use Vue.js runtime yet.

**Comment by wxsms** [comment]
in your console log, there appears to have 2 vue running in the same time: `vue.runtime.esm.js` and `vue.esm.js`. This should be the root cause. same as #119

**Comment by markgajdosik** [comment]
Hi wxsms, thank you for pointing that out. I am not sure why both libraries appear in the traceback. We only ever import `vue.esm.js` ... perhaps it's importing the runtime internally?

We will move all remaining Vue code in HTML/JS files into components and switch to the runtime to get rid of the warnings.
