### ISSUE TITLE
customize datepicker year month label format

### ISSUE THREAD

**Issue by danieltutu** [wxsms/uiv#204]
I already asked a question about this issue: https://stackoverflow.com/questions/49916408/customize-vuejs-datepicker-for-bootstrap-3/49917130#49917130

Recently the need to to change the format from `2018 April` to `April 2018` came up.

I think it would be a good idea to have a way to customize the format of this label.

I am not sure about the naming of this parameter and its format.

What do you think?

**Comment by wxsms** [comment]
I think that a formatter callback function  will be good enough.
