### ISSUE TITLE
Suggestion: show week numbers in date picker 

### ISSUE THREAD

**Issue by llvdl** [wxsms/uiv#206]
Hello,

Thanks for creating this useful library.

I am currently using the date picker component, among other components. The users for the application I am working on often plan using week numbers and showing these in the data picker would really help.

Would it be possible to show week numbers in the date picker? 

I have a created an example of how this could be visualized:

![image](https://user-images.githubusercontent.com/6775525/39267377-e40a0b98-48cc-11e8-85de-f1e61339f444.png)

In my region weeks start on Monday  as per [ISO 8601](https://en.wikipedia.org/wiki/ISO_week_date), but the starting day could be set to the `:week-starts-with` prop.

**Comment by wxsms** [comment]
Thanks for the advise.

**Comment by llvdl** [comment]
Thanks for the very quick response! 

I have enabled the week numbers in my project and it works great.

The week numbers require some extra space, but that was easy to adjust using the `width` prop.
