### ISSUE TITLE
Multiselect optgroups

### ISSUE THREAD

**Issue by tbcaro** [wxsms/uiv#207]
Hi, 

I would like to use the `<multi-select>` component. Currently, for my workflow I need the ability to use `<optgroup>`'s

Would it be possible to add `<optgroup>` support? 

Thanks for all the work that you do!

**Comment by jblotus** [comment]
Yes this would be a great enhancement

**Comment by jblotus** [comment]
For now, I'm thinking I can use the disabled feature to emulate optgroups by placing a disable option first in each "group".

**Comment by wxsms** [comment]
@tbcaro @jblotus you may give it a try in next release.

**Comment by jblotus** [comment]
looks great!
