### ISSUE TITLE
When modal is open and browser goes back one route, the body remains unscrollable

### ISSUE THREAD

**Issue by leehsueh** [wxsms/uiv#209]
### Which component
Modal when using client-side routing history

### Steps to reproduce the problem
1. Navigate to various frontend routes
2. On a page with a modal, invoke the modal
3. Click back to go to a previous route
4. The modal is removed, but the body still has the `modal-open` class on it

### Expected behavior
If the modal and backdrop is removed, the body should become scrollable again

### Actual behavior
When a route change causes the modal to be destroyed (modal and backdrop removed), the body element cannot be scrolled because of a lingering `modal-open` class.

**Comment by wxsms** [comment]
PR merged. thanks!

**Comment by jblotus** [comment]
In my case, this fix did not work. I am navigating using vue-router programatically via $router.push()

The check for open modals is still detecting the backdrop in this case and the cleanup does not run.

To get around this I manually call $destroy() on the modal component before invoking navigation and cleanup runs properly.
