### ISSUE TITLE
Add popover viewport option

### ISSUE THREAD

**Issue by fabscav** [wxsms/uiv#213]
The bootstrap popover has an option to set the "viewport", keeping the popover within the bounds of the specified element (https://getbootstrap.com/docs/3.3/javascript/#popovers-options). It would be very nice if this could be incorporated into uiv. 

Great work on the library btw, big fan 👍

**Comment by wxsms** [comment]
Thanks. I'm not familiar with this prop, may need some time to study a little.

**Comment by seyfer** [comment]
It is really needed. Otherwise, popover and tooltip are out of the screen sometimes, so I cannot use UIV at all without this option.

**Comment by wxsms** [comment]
@fabscav @seyfer it's done.

**Comment by seyfer** [comment]
@wxsms great! :tada:
