### ISSUE TITLE
SSR bootstrap.min.css.map is getting add at my query string

### ISSUE THREAD

**Issue by jericopulvera** [wxsms/uiv#214]
{ 
Error: Request failed with status code 404
Path: '/api/v1/u/community-posts-comments?communityPostId=bootstrap.min.css.map&from=0&limit=5',
}

**Comment by wxsms** [comment]
sry but I don't understand.

**Comment by wxsms** [comment]
this lib has nothing to do with `bootstrap.min.css.map`. not included in anywhere. pls check your own project.
