### ISSUE TITLE
No table?

### ISSUE THREAD

**Issue by ycmbcd** [wxsms/uiv#218]
I need BoosStrap3's  【table】 function，3Q

**Comment by lantern77** [comment]
If you include the bootstrap css.
Calling
```
<table class="table">
</table>
```
Would work there's not much with tables to create custom functions no?

**Comment by ycmbcd** [comment]
Let me try try

**Comment by wxsms** [comment]
as @lantern77 said, there're not much to do with Bootstrap's table. If you need advance functions (like sorting), pls use other datatable plugin for Vue instead. Thanks!
