### ISSUE TITLE
DatePicker translation

### ISSUE THREAD

**Issue by SzNagyMisu** [wxsms/uiv#219]
Hullo there,
Is there any possibility to internationalize a _DatePicker_ component without the need to install the whole plugin with `Vue.use(Uiv, { locale: myLocale })`?
For example being able to pass a locale object / json in `props`?
Would appreciate a lot.

Thanks in advance!

**Comment by wxsms** [comment]
sry, there're currently no solution for this. you need to install it if i18n is needed.

**Comment by wxsms** [comment]
this might work:

```javascript
import locale from 'uiv/src/locale'

locale.use(yourLocale)
```

**Comment by SzNagyMisu** [comment]
Tried it, didn't work. Thanks for it anyway.

First, I put it in `src/main.js`, then in the component that uses _UivDatePicker_, but had absolutely no effect. After, I thought I had to use _UivDatePicker_ from the source code, so I changed

    import { DatePicker as UivDatePicker } from 'uiv'
to

    import UivDatePicker from 'uiv/src/components/datepicker/DatePicker'
and then it had the strange effect of translating everything to `undefined`. So I had neither month nor weekdays, nor even today and clear button texts.

**Comment by SzNagyMisu** [comment]
A small modification on _localeMixin_ would solve my problem, though.
What if - as I suggested when opening the issue - I could send a locale object as props?

So `src/locale/index.js` would look like this?

    import locale from '../locale'
    export default {
      methods: {
        t (...args) {
          return locale.t.apply(this, args)
        }
      },
      props: { locale: Object },
      created () { locale.use(this.locale) }
    }

**Comment by wxsms** [comment]
Thanks. This looks good. PR is welcome.

**Comment by SzNagyMisu** [comment]
Almost ready with th PR, but ran into a problem.
I Made the changes, updated the docs, wrote the test which passes, but when I run the whole suite, it breaks 9 previous tests.
The problem is that `locale.use(myLocale)` changes the `lang` globally. So if I try

    <template>
      <date-picker :locale="localeFR" />
      <date-picker :locale="localeHU" />
    </template>

both `date-picker`s will use the HU locale. Accordingly, every test that checked on the text of any uiv component will break because it will compare the English translation to the Hungarian one. Also the whole documentation may change to use the Hungarian locale.

Maybe, would it be possible to pass a `locale` property to the `options` parameter of the function `t`? Then it could use this for custom localization.

**Comment by wxsms** [comment]
I see. you should not use `created () { locale.use(this.locale) }` then. You may try to pass the locale prop to `t`, this should be better, but you have to also modify the t function, something like this:

```javascript
export const t = function (path, options) {
  ...
  let current = options.$$locale || lang
  ...
}
```

But another problem is, if you also have vue-i18n installed, this won't work. you have to check if `$$locale` exist and apply such translation and return the value before using `i18nHandler`.

**Comment by wxsms** [comment]
wait a min... I just notice that, you can achieve your goal (internationalize a DatePicker component without the need to install the whole plugin) by using `vue-i18n`. since this will skip the plugin's translation function.

**Comment by SzNagyMisu** [comment]
Opened the PR.

BTW, why the **$$** for `options.$$locale`?

**Comment by wxsms** [comment]
because the `options` is for vue-i18n plugin, $$ makes it not that easy to conflict with something.

**Comment by wxsms** [comment]
It's done in v0.24.0, thanks.
