### ISSUE TITLE
Popover: when title is empty, should no title-node

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#22]
Now:
<img width="239" alt="2017-04-19 14_21_54-uiv - bootstrap 3 components built with vue 2" src="https://cloud.githubusercontent.com/assets/15178410/25165999/bdd2ed5e-250b-11e7-80e3-c9c101c3c9f5.png">

Expect:
<img width="239" alt="2017-04-19 14_22_12-uiv - bootstrap 3 components built with vue 2" src="https://cloud.githubusercontent.com/assets/15178410/25165998/bc69e706-250b-11e7-9cf7-f018b699c5ba.png">

**Comment by wxsms** [comment]
available on next release
