### ISSUE TITLE
Add Class to Tabs for custom styling

### ISSUE THREAD

**Issue by lantern77** [wxsms/uiv#220]
On the Tabs.vue component, on line 5. Can we update the function 'getTabClasses' to accept an additional prop or field so that we can add classes to the tab itself. 

Use:  currently we would like to add a class to the tab, but adding a class to uiv tabs adds the class to the tab-content. This could be useful for differently colored tabs.

Code Reference:
https://github.com/wxsms/uiv/blob/b82a236b7f15cdf2c4e7bf6419d94f2ab04227fe/src/components/tabs/Tabs.vue#L5

If approved I can or someone can make the addition.

**Comment by lantern77** [comment]
Sure that sounds even better actually, this will be done under Tab.vue I believe? Will you be committing or should I make a pull request?

**Comment by wxsms** [comment]
PR is welcome if you wish to. Thanks!

**Comment by lantern77** [comment]
Will do I will add when I am free this weekend.

**Comment by marlonbarcarol** [comment]
I noticed that in the documentation we have a small mismatch with the actual code. The prop in the docs should be `tab-classes` instead of `tab-class`.

**Comment by wxsms** [comment]
@marlonbarcarol Thanks, fixed now.
