### ISSUE TITLE
Separating a Modal into its own component vue

### ISSUE THREAD

**Issue by ventralnet** [wxsms/uiv#226]
Having your `<modal>` declaration in the same template that will control spawning it is trivial because the v-model open and closed flag can be handled by a data variable.  I am having trouble with including a custom Vue component that spawns the modal based of a prop.  Vue2 will warn you that uiv Modal is updating a prop directly which is an anti-pattern in vue2.  Note: I am new to Vue so bear with me

"Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: 'value'"

Vue2 is trying to avoid a child component modifying a parent components data which is understandable.

I have tried a solution similar to this https://stackoverflow.com/questions/49315487/vuejs-error-avoid-mutating-a-prop-directly but @hide is never called in that situation (although it does remove the Vue warning from the console).

I am not sure if this is a bug? But any help would be appreciated.  

```
// MyParent.vue
<template>
  <div>
    <my-custom-modal v-model="isOpen" />
    <button @click="isOpen = true">Open Modal</button>
  </div>
<template>

<script>
import MyCustomModal from './MyCustomModal.vue';

export default {
   components: {
      MyCustomModal
   },
   data() { return { isOpen: false } },
}
```

```
// MyCustomModal.vue
<template>
  <section>
    <modal
        v-model="value"
        @hide="callback"
        :append-to-body="true">
        <p>Modal body</p>
    </modal>
   </section>
</template>

<script>
import { Modal } from 'uiv';

export default {
   components: {
      Modal
   },
   props: {
      value: Boolean
   },
  methods: { hide(msg) { console.log('hide ', msg);  }}
}
</script>
```

**Comment by wxsms** [comment]
you should not use the prop directly as the v-model of modal. use data instead.

```vue
// MyCustomModal.vue
<template>
  <section>
    <modal
        v-model="show"
        :append-to-body="true">
        <p>Modal body</p>
    </modal>
   </section>
</template>

<script>
import { Modal } from 'uiv';

export default {
   components: {Modal},
   props: {
      value: Boolean
   },
  data () {
    return {show: false}
  },
  watch: {
    show (v) {
      this.$emit('input', v)
    }
  }
}
</script>
```

**Comment by ventralnet** [comment]
@wxsms thanks for you response and you work on this library.

This was a strategy I was exploring however I wasn't sure if it was the right way.  I suppose I listed this as a bug because I question if the modal should modify the 'open' and 'closed' state.  Seems like whatever uses the modal should be concerned about when to show and close the modal and not the modal itself.

But anyhow, thanks for the response, I will probably go with this strategy.

**Comment by wxsms** [comment]
It's for easier usage. Otherwise you have to implement `onShow` & `onClose` event on every modal instance. It will be like this if this is a React lib, but in Vue `v-model` should be better I think.

**Comment by ventralnet** [comment]
@wxsms Sounds good I see your reasoning.

A question with the code snippet you responded with.  If you are watching the `show` data how would the modal every initially open.

1. Parent clicks button which sets reactive prop `value` to true
2. `show` data property is never updated to true so modal never displays

**Comment by wxsms** [comment]
you can add a watcher to `value` too.
