### ISSUE TITLE
Dropdown in Safari on iOS: clicking does not close dropdown

### ISSUE THREAD

**Issue by fikkatra** [wxsms/uiv#230]
### Version & browser
iOS 11 on iPhone X, Safari

### Which component
Dropdown

### Steps to reproduce the problem
- Open the codepen below in Safari on iPhone
- Click the dropdown => it opens => OK
- Click on one of the items in the dropdown => dropdown does not close => NOK
- Click outside of the dropdown => dropdown does not close => NOK

Also tested this in other browsers: Chrome on Windows, Chrome on Android, Safari on Mac OS => everything works fine.

### Reproduce link
https://codepen.io/anon/pen/gjgpYK

### Expected behavior
The dropdown should close when clicking either inside or ouside of the dropdown.

### Actual behavior
The dropdown does not close.

**Comment by wxsms** [comment]
I see. thanks.
