### ISSUE TITLE
Typeahead: possibility to specify property to be bound to model

### ISSUE THREAD

**Issue by fikkatra** [wxsms/uiv#233]
With `item-key` I can specify which property of an item should be displayed in the typeahead. The model, however, is always bound to the item itself. It would be nice if I could also specify which item property to bind to the model.

For example, I have a list of customer items. I want to display the name of the customer, but I want to bind the model to the id of the customer.

This could look something like this:
```
let customers = [
	{
		id: 1,
		name: "John"
	},
	{
		id: 2,
		name: "Jane"
	}
]
```

```
<input id="customerInput" class="form-control" type="text" placeholder="Type to search...">
<typeahead v-model="customerId" target="#customerInput" :data="customers" item-key="name" item-value="id"/>
```

This is analogous to the following Angular Bootstrap code:
`<input type="text" ng-model="customerId" uib-typeahead="c.id as c.name for c in customers">`

**Comment by wxsms** [comment]
Thanks for the advice. In Vue.js you can simply use [computed](https://vuejs.org/v2/guide/computed.html#Computed-Properties) to achieve this. I don't think that a `item-value` implementation is necessary.

**Comment by fikkatra** [comment]
Yes, you can use computed to GET computed properties, but in this case I want to SET a property (v-model). But maybe I don't understand properly what you mean. Could you explain by extending my example (customer list)?

**Comment by wxsms** [comment]
This is not logical. For example, you have a **async** typeahead with both `item-key` and `item-value` set, how is it possible to get the `item-key` with only `item-value` given?

If you want to set a property, just pass the correct item to `v-model`, then you can read from computed value.

**Comment by wxsms** [comment]
Feel free to continue discuss if any questions.
