### ISSUE TITLE
Adding `input` event to [Pagination] docs

### ISSUE THREAD

**Issue by SzNagyMisu** [wxsms/uiv#235]
Hi,

Can I add the `input` event to the [docs](https://uiv.wxsm.space/pagination/#api-reference) of `Pagination`? According to the source code it emits `change` and `input` events with the same payload. Should I write a test for it?

**Comment by wxsms** [comment]
Actually `input` event is used by `v-model`, I think it's not necessary.

**Comment by SzNagyMisu** [comment]
I see, OK.
