### ISSUE TITLE
Enhancement of [Modal] with new props

### ISSUE THREAD

**Issue by SzNagyMisu** [wxsms/uiv#236]
Using `Modal` I found that some additional `props` would make my life easier. I would like to have your opinion if some (or all) of these can have a place in the component:

- `ok-type`, `cancel-type`: as implemented in `MessageBox`
- `ok-icon`, `cancel-icon`: passing a string like 'trash' or 'save' to have a corresponding `glyphicon` before the text of the button - it would be nice to have this in `MessageBox` too
- `title-icon` or `title-html`: for the same reason

Thanks in advance!

**Comment by wxsms** [comment]
Hi. My opinion:

1. `ok-type`,  `cancel-type` are acceptable.
2. As for icon & HTML titles, since there're already `header` and `footer` slot exist, I'd like to keep it simple.

**Comment by SzNagyMisu** [comment]
Great, thanks!
Should I provide a PR?
As for `2.`, what do you think about `MessageBox` buttons and title?

**Comment by wxsms** [comment]
PR is welcome.

As the doc states:
By design MessageBox provides simulations of browsers' `alert`, `confirm` and `prompt`. Use Modal instead if needed more complicated contents.

**Comment by SzNagyMisu** [comment]
OK, understood :-)
I will provide a PR for `ok-type` and `cancel-type` props of `Modal`, then.

**Comment by wxsms** [comment]
Thanks!
