### ISSUE TITLE
Typeahead: Not possible to select item from dropdown on mobile device

### ISSUE THREAD

**Issue by frednijs** [wxsms/uiv#238]
### Version & browser
A mobile device or Chrome on desktop impersonating a mobile device

### Which component
Typeahead

### Steps to reproduce the problem
Search in de typeahead until there is a dropdown with results and select one of the results.

### Reproduce link
https://uiv.wxsm.space/typeahead/#typeahead-2

### Expected behavior
The result is selected and displayed in the input element.

### Actual behavior
The result is not selected.

**Comment by wxsms** [comment]
Looks like a bug cause by #230
