### ISSUE TITLE
Add event after-change on tabs

### ISSUE THREAD

**Issue by zajca** [wxsms/uiv#239]
Hi,
would be great if event is triggered when tab actually shows on screen.
I run into one issue. I have component which is rendered based on self width. So when `mounted/resize/updated` method is called which will call `getBoundingClientRect` and calculate it's properties. But when I recalculate on tabs `change` event tab with `activeIndex` has still `display: none`. Event when tab get `active` class would solve this.

**Comment by wxsms** [comment]
Added `after-change` event on next release.
