### ISSUE TITLE
MessageBox ($confirm) does not respect ok-type, ok-text, ...

### ISSUE THREAD

**Issue by markgajdosik** [wxsms/uiv#243]
### Which component
MessageBox

### Steps to reproduce the problem
1. Create a 'confirm' message-box.
2. Customise ok-text, ok-type, cancel-text, cancel-type as required.

### Reproduce link
https://codepen.io/anon/pen/PdGoYR

### Expected behavior
OK and/or cancel buttons should adopt the text/types assigned to them.

### Actual behavior
OK and/or cancel buttons remain as default.

**Comment by wxsms** [comment]
Sry, this should be a doc mistake. Pls use `okType`, `okText`, ect..
