### ISSUE TITLE
Typeahead position

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#25]
### Provide a option to auto width as `input`
> use `min-width` instead of `width`

Now:
<img width="312" alt="2017-04-21 15_42_43-wecenterz" src="https://cloud.githubusercontent.com/assets/15178410/25268636/0d328ac0-26ac-11e7-9cc1-10a6456ef02d.png">

Expext:
<img width="247" alt="2017-04-21 15_44_30-wecenterz" src="https://cloud.githubusercontent.com/assets/15178410/25268637/0d797052-26ac-11e7-9adb-9eace55d9422.png">

---

### Proper position when in `navbar`

Demo code:
```html
<nav class="navbar navbar-toolbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" @click="showNavbar=!showNavbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Brand</a>
    </div>
    <collapse class="navbar-collapse" v-model="showNavbar">
          
      <form class="navbar-form navbar-right">
        <div class="input-group">
          <typeahead v-model="model2"
                async-src="https://api.github.com/search/users?q="
                async-key="items"
                item-key="login">
            <input data-role="input" class="form-control" type="text" placeholder="Type to search...">
            <template slot="item" scope="props">
              <img width="22px" height="22px" :src=" props.item.avatar_url + '&s=40' ">
              <span v-text="props.item.login"></span>
            </template>
          </typeahead>
          <span class="input-group-btn">
            <button class="btn btn-default">
              <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              <span class="sr-only">搜索</span>
            </button>
          </span>
        </div>
      </form>
          
    </collapse>
  </div>
</nav>
```

Now on mobile:
<img width="312" alt="2017-04-21 16_44_35-wecenterz" src="https://cloud.githubusercontent.com/assets/15178410/25270112/f8fe9714-26b1-11e7-930d-b2737cbf9df5.png">

Now on desktop:
<img width="464" alt="2017-04-21 15_58_04-wecenterz" src="https://cloud.githubusercontent.com/assets/15178410/25268638/0d79ff54-26ac-11e7-92d0-cb643c0ce3a2.png">

**Comment by wxsms** [comment]
> Provide a option to auto width as input

I will see if it is really necessary.  **currently you can add `right: 0` to the relative `dropdown-menu` element to get to this**. 

However, it will not work on `append-to-body` case.

> Proper position when in navbar

Just try your case, **it will position correctly** if you use the proper markup and classes as bootstrap defined.

```html
<form class="navbar-form navbar-right">
  <typeahead class="form-group"
             v-model="model1"
             :data="states"
             :item-key="itemKey"
             :limit="10">
    <div class="input-group">
      <input data-role="input" class="form-control" type="text" placeholder="Type to search...">
      <span class="input-group-btn">
        <button class="btn btn-default">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          <span class="sr-only">搜索</span>
        </button>
      </span>
    </div>
  </typeahead>
</form>
```

BTW, it's better to add `append-to-body=true` to this case since the collapse part has `overflow: hidden` style when on mobile.

**Comment by zcyzcy88** [comment]
> Just try your case, **it will position correctly** if you use the proper markup and classes as bootstrap defined.

Not yet.
- I don't want to wrap with a `<div>`
- I don't want to put the submit button in `<typeahead>`
- I have no idea why it is still override with `append-to-body=true` 
<img width="475" alt="2017-04-26 02_32_42-wecenterz" src="https://cloud.githubusercontent.com/assets/15178410/25401620/cf342c58-2a28-11e7-8b69-c5693d5cce33.png">

**Comment by zcyzcy88** [comment]
```vue
<typeahead v-model="selected"
    async-src="https://api.github.com/search/users?q="
    async-key="items"
    item-key="login"
    :append-to-body="true">
  <div class="input-group">
    <input data-role="input" class="form-control" type="text" placeholder="Type to search...">
    <span class="input-group-btn">
      <button class="btn btn-default">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        <span class="sr-only">搜索</span>
      </button>
    </span>
  </div>
  <template slot="item" scope="props">
    <img width="22px" height="22px" :src=" props.item.avatar_url + '&s=40' ">
    <span v-text="props.item.login"></span>
  </template>
</typeahead>
```

Ugly.
I don't want to put the submit button in `<typeahead>`.
I don't want to wrap with a `<div>`.


---

You use the relative position, this will cause problem in navbar (because there are some override CSS for dropdown in navbar)

<img width="1001" alt="2017-04-26 03_01_25-navbar vue_ - microsoft visual studio" src="https://cloud.githubusercontent.com/assets/15178410/25402933/0c4e6492-2a2d-11e7-89b6-2fbefbe608e3.png">
<img width="679" alt="2017-04-26 03_01_00-navbar vue_ - microsoft visual studio" src="https://cloud.githubusercontent.com/assets/15178410/25402934/0c56b2e6-2a2d-11e7-9809-8d4b1f6ba5ad.png">

So you should hard calculate position:
```js
// pseudo code
$menu.style.top = $input.offset.top + $input.height
$menu.style.top = $input.offset.left
```

**Comment by wxsms** [comment]
The position **is hard caculated** if using `append-to-body`.

It doesn't matter where to put the submit button. &lt;Typeahead&gt; just create a simple div for DOM but nothing else. The key is to make the input element positionable. If it's display set to `inline` then it will be no height, which cause your problem.

**Comment by zcyzcy88** [comment]
My case solution:
```vue
<form class="navbar-form navbar-left">
  <typeahead v-model="selected"
             async-src="https://api.github.com/search/users?q="
             async-key="items"
             item-key="login"
             class="input-group"
             append-to-body="true">
    <div class="input-group">
      <input data-role="input" class="form-control" type="text" placeholder="Type to search...">
      <span class="input-group-btn">
        <button class="btn btn-default">
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          <span class="sr-only">搜索</span>
        </button>
      </span>
    </div>
    <template slot="item" scope="props">
      <img width="22" height="22" src=" props.item.avatar_url + '&s=40' ">
      <span v-text="props.item.login"></span>
    </template>
  </typeahead>
</form>
```

Note:
- Add `<template slot="item">` as direct child of `<typeahead>`
- Add `class="input-group"` on `<typeahead>` for some theme (e.g. TODC)

<img width="600" alt="2017-04-27 20_15_28-wecenterz" src="https://cloud.githubusercontent.com/assets/15178410/25483281/bdbe8b48-2b87-11e7-9784-fe832419ca56.png">

---

Now it is worked, but I should explain my word on the previous comment.

You hard caculated the position of [`ref="dropdown"`](https://github.com/wxsms/uiv/blob/master/src/components/typeahead/Typeahead.vue#L4) , not the [`inputEl`](https://github.com/wxsms/uiv/blob/master/src/components/typeahead/Typeahead.vue#L93) .
In another word, you do:
```js
$menu.style.position.absolute
$menu.style.top = $dropdown-container.offset().top + $dropdown-container.height
$menu.style.top = $dropdown-container.offset().left
```

**Comment by wxsms** [comment]
OK. I will fix this.
