### ISSUE TITLE
how can we keep a popover alive while the popover is being hovered?

### ISSUE THREAD

**Issue by fperniavp** [wxsms/uiv#250]
I'm trying to trigger manually the popover using trigger="manual" with a hover event:

```
<template>
  <section>
    <popover title="Title" trigger="manual" v-model="show">
    <template slot="popover">
        <p>Popover content</p>
      </template>
    </popover>
    <hr/>
    <!--see @mouseover and @mouseleave bellow-->
    <btn type="primary" @mouseover="show=true" @mouseleave="show=false">Toggle Popover</btn>
  </section>
</template>
<script>
  export default {
    data () {
      return {
        show: false
      }
    }
  }
</script>
```

Well, I understand why the popover is being closed due when I leave the button I set `show` to `false`.

So my question is: Where do I have to place that `@mouseleave` event in order to prevent closing the popover when it is being hovered?

**Comment by wxsms** [comment]
you can add `@mouseenter.native` & `@mouseleave.native` to `<popover>`.

**Comment by fperniavp** [comment]
I've found an alternative for this:

```
<popover trigger="hover" title="Title">
    <a href="#" @click.prevent>Toggle Popover</a>
    <template slot="popover">
       <p>Popover content</p>
     </template>
 </popover>
```

Basically, we can use ```trigger="hover"``` to prevent closing the popover when it is being hovered

You can check this here: https://plnkr.co/edit/RSjhazfxqBhaNqcKijXe?p=preview
