### ISSUE TITLE
Datepicker Today button fails when focus is not Datepicker

### ISSUE THREAD

**Issue by mbokil** [wxsms/uiv#252]
### Version & browser
Firefox 63

### Which component
Datepicker

### Steps to reproduce the problem
From the demo page click the next month button in Datepicker. Click the page outside of the Datepicker. Now click the Today button. Notice the calendar doesn't change to today. Now click the calendar and pick any day. Click the today button and it correctly goes to today. Appears if Datepicker is not in focus Today button fails. 

### Reproduce link
https://uiv.wxsm.space/date-picker

### Expected behavior
Clicking Today always goes to today

### Actual behavior
The calendar remains unchanged and today is not selected

**Comment by wxsms** [comment]
This is actually not about focus, I think. If today is already selected, then you select another month/year, then click today, it will not jump to the correct month&year. This might be the problem.
