### ISSUE TITLE
Documenting changes properly

### ISSUE THREAD

**Issue by locolauty97** [wxsms/uiv#254]
Hi, I just want to make a critic about the way of releasing changes to production. Until this date, I think the last made change is the addition of the `after-change` event on the Tabs component.

The problem is that in the docs of the project, there's no documentation about in what release something was introduced, so I was trying to use the `after-change` event without success because didn't have it in my project at all. Should be documented with the version code of the release.

That's all, just a comment that I think can help make this project better for others.

The project is awesome! Thanks for all.

**Comment by wxsms** [comment]
Good point, thanks for the advice.

**Comment by wxsms** [comment]
Added new feature version to the document in recent releases.
