### ISSUE TITLE
Tooltip (and popover) works differently in Firefox vs Chrome on disabled content

### ISSUE THREAD

**Issue by anlek** [wxsms/uiv#258]
### Version & browser
Chrome: Version 70.0.3538.77
Firefox: (DeveloperEdition) 64.0b4

### Which component
Tooltip and Popover

### Steps to reproduce the problem
```
tooltip(text="Help me")
  div.btn(disabled="disabled")
```

### Reproduce link
N/A

### Expected behavior
Firefox:
![2018-11-01 16 06 34](https://user-images.githubusercontent.com/11052/47876704-5273a400-ddf0-11e8-9805-461fd567c24c.gif)

### Actual behavior
Chrome:
![2018-11-01 16 07 22](https://user-images.githubusercontent.com/11052/47876709-569fc180-ddf0-11e8-9a53-6b5d7f4519a1.gif)

### Temp fix
I was able to fix it by adding a `div` around the `.btn` div
```
tooltip(text="Help me")
  div
    div.btn(disabled="disabled")
```

**Comment by wxsms** [comment]
Looks like chrome has prevented native mouse events like `mouseenter` with disabled elements, and I found no workarounds. Your temp fix maybe the only way to allow so. do you have any suggestions?

**Comment by wxsms** [comment]
close due to no solution. feel free to continue discuss if any idea.
