### ISSUE TITLE
[Feature request] Tabs with ajax loaded content

### ISSUE THREAD

**Issue by stephanvierkant** [wxsms/uiv#262]
I want a tab with ajax loaded content. Something like this:

```
<uiv-tabs>
    <uiv-tab title="Ajax loaded tab" url="{url}"></uiv-tab>
</uiv-tabs>
```

**Comment by wxsms** [comment]
This is not a best practice of Vue.js. I suggest you to have a look at how to handle ajax contents in Vue.js.
