### ISSUE TITLE
bootstrap-switch component for checkbox 

### ISSUE THREAD

**Issue by Alideniz** [wxsms/uiv#263]
I was thinking about checkbox. İt is looking very awful when we use native HTML checkbox. İt can be more useful and meaningful if it is switch-toggle for  the user experience.

**Comment by wxsms** [comment]
？

**Comment by Alideniz** [comment]
I updated description

**Comment by wxsms** [comment]
to keep this lib simple and elegant, no extra css will be added.

you may use some pure css solutions, something like: https://codepen.io/aanjulena/pen/ZLZjzV
