### ISSUE TITLE
Backdrop problem with modal style zIndex

### ISSUE THREAD

**Issue by Pasalietis** [wxsms/uiv#264]
When you specifie zIndex for modal style. For example: `<uiv-modal style="z-index: 10020;">...</uiv-modal>`. Backdrop do not inherit zIndex so it may happen then backdrop is under element with higher zindex

**Comment by wxsms** [comment]
you need to change the model & backdrop zIndex yourself as well. it's not a job of this lib to fit all kinds of custom styles.
