### ISSUE TITLE
Datepicker should return a Date object instead of a formatted string

### ISSUE THREAD

**Issue by prbaron** [wxsms/uiv#265]
The datepicker currently returns a formatted string which means we lose the timezone. I think the datepicker should get a Date object as input and provide a Date object as output. The format is not the component's responsibility.

This would also make the datepicker and timepicker consistent in their API.

**Comment by wxsms** [comment]
What if it emits a Date object while `format` is provided as empty string?

**Comment by prbaron** [comment]
That is fine by me, it would keep the compatibility with the current code.
