### ISSUE TITLE
Feature request: Add customClass to Tabs

### ISSUE THREAD

**Issue by RomeroMsk** [wxsms/uiv#266]
I need to set an extra class for `ul.nav-tabs`. But as of root element in `Tabs` component is `<section>`, the only way I see is to implement a property (something like `customClass` in `Notification`). Could you please add this functionality?

**Comment by wxsms** [comment]
add `:class` to Tabs will work.

**Comment by RomeroMsk** [comment]
No, it will set the class on `<section>` and not `<ul>`.

**Comment by wxsms** [comment]
I see.

**Comment by RomeroMsk** [comment]
Thanks.
