### ISSUE TITLE
Turning off auto-focus on MessageBox.

### ISSUE THREAD

**Issue by anlek** [wxsms/uiv#270]
I love the MessageBox component and I appreciate the fact that it auto focuses the "OK" button. However, I hit a situation where I don't want OK to be focused, I want cancel to be focused as the user might accidently hit 'enter' or 'spacebar' on the keyboard before reading the super important message.

### Version & browser
uiv: 0.28.0
chrome: 72.0.3626.96

### Which component
MessageBox

### Steps to reproduce the problem
```javascript
this.$confirm({
        title: 'Ending The World',
        content: `Are you sure you want to end the world? This CANNOT be UNDONE!`,
        okType: 'danger',
        okText: 'END!',
        backdrop: false,
      })
        .then(() => {
           this.pureEvil.call()
        })
        .catch(() => {
          // User changed their mind, NOOP
        })
```
### ~Expected~ Wanted behavior
The auto-focus to be on cancel (to avoid accidental keyboard pressing of "END!"). As a fallback, I'd be fine if auto focus is turned off and nothing is in focus (forcing the user to move the mouse to click desired action)

### Actual behavior
OK (or in this case "END!") is focused.

**Comment by wxsms** [comment]
Thanks for the feedback. I will add a new prop for this feature.
