### ISSUE TITLE
SVG element causes script error

### ISSUE THREAD

**Issue by elmahdi-dev** [wxsms/uiv#271]
Hello,

First thank you for this great library! I'm here to report a bug I've found while using uiv on my project. I've noticed that when using uiv, after the page has loaded, the first click look for all html elements with a tooltip, and as soon as the element is a SVG, it causes script errors, while they dont prevent the library from working properly, I still wanted to share it with you.

The problem is located here :

``` javascript
    windowClicked: function windowClicked(event) {
      if (this.triggerEl && !this.triggerEl.contains(event.target) && this.trigger === TRIGGERS.OUTSIDE_CLICK && !this.$refs.popup.contains(event.target) && this.isShown()) {
        this.hide();
      }
    },
```
For some reason, if the triggerEl object is an SVG an error is thrown in the console :

> SCRIPT438: Object doesn't support property or method 'contains'

To solve this problem I check if .contains is a function type, (typeof this.triggerEl.contains === 'function'), the result determine if I continue or I return.

### Version & browser
v0.31, IE9

### Which component
tooltip

**Comment by wxsms** [comment]
Thanks for the feedback.
