### ISSUE TITLE
Unenterable popovers keep disappearing & reappearing in quick succession

### ISSUE THREAD

**Issue by markgajdosik** [wxsms/uiv#272]
### Version & browser
Chromium Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

### Which component
Popover

### Steps to reproduce the problem
1. Create a button with id="test"
2. Create a popover with:
`<popover :enterable="false" placement="right" trigger="hover" target="#test">`
3. Hover the mouse pointer over the right edge (border) of the button.

### Expected behavior
Popover stays visible when hovering over the button and hidden when not hovering over the button.

### Actual behavior
The popover will start appearing/disappearing in a quick succession.

**Comment by wxsms** [comment]
I can't reproduce this on Mac chrome...  are you using the latest uiv version?

**Comment by markgajdosik** [comment]
https://codepen.io/anon/pen/pYgjwy

You need to be on the right border of the button for this to happen. Also, Firefox does not seem to have this issue. I manage to capture the behaviour on video:

[Screencast 2019-03-01 00:20:10.zip](https://github.com/wxsms/uiv/files/2917427/Screencast.2019-03-01.00.20.10.zip)

**Comment by wxsms** [comment]
I see.
