### ISSUE TITLE
Tooltip doesn't appear in firefox when attached to element within a button

### ISSUE THREAD

**Issue by tinyfly** [wxsms/uiv#273]
### Version & browser
* Vue 2.6.7
* uiv 0.31.1
* Firefox 65.0.1 (Mac OS)

### Which component
Tooltip

### Steps to reproduce the problem
1. Create a button with a span inside and text inside the span
2. Attach the tooltip directive to the span that is in the button
3. Try hovering over the span to trigger the tooltip in Firefox

### Reproduce link
https://codepen.io/tinyfly/pen/QYReOK

### Expected behavior
Tooltip appears in all browsers

### Actual behavior
Tooltip doesn't appear in Firefox but it works fine in all others.

**Comment by tinyfly** [comment]
Perhaps this is by design according to the [HTML 5 Spec](https://dev.w3.org/html5/spec-LC/the-button-element.html):

> **Content model:**
> Phrasing content, but there must be no **interactive content** descendant.

So maybe Firefox is following the spec and you won't get any events from content within a button. However, Edge, Safari, Opera, and Chrome all work fine in this case.

**Comment by wxsms** [comment]
Do you have any suggestions?

**Comment by tinyfly** [comment]
I don't think so other then use a `<a>` tag instead or something. I guess if you don't have any ideas on how to make this work with a button on Firefox then feel free to close this.

**Comment by wxsms** [comment]
Thanks for the feedback. But I do have no idea on how to fix this. Feel free to let me know if you got some idea.

**Comment by tinyfly** [comment]
FYI, I just tested this again in Firefox 67 and it seems to work as expected now.
