### ISSUE TITLE
Is it possible to change where the modal-backdrop element is appended?

### ISSUE THREAD

**Issue by abaracedo** [wxsms/uiv#274]
I have started working in a project that is using this package and I have seen that the `modal-backdrop` element is appended before closing the `body`.

Is it possible to make that element appear next to the modal element?

**Comment by abaracedo** [comment]
I have seen there is a prop to append the modal into the `body`. I was having some issues where the backdrop was over the modal.

**Comment by wxsms** [comment]
In what cases you needed to append it to other elements?

**Comment by abaracedo** [comment]
Before knowing about the option to append the modal to the body, always.

The modals where appended into the component where was included it and in some cases some of the components had a fixed position and for reasons that I don't know (I didn't create the project) some components had a different `z-index`.

**Comment by wxsms** [comment]
Currently there're no option to do that. there will be some side effects if the append target changed. If `z-index` is the cause of your problem, then I suggest you to change the backdrop zIndex with css rather than append it to other elements.
