### ISSUE TITLE
[Multiselect] Dropdown disappear after clicking on item selection 

### ISSUE THREAD

**Issue by etino** [wxsms/uiv#278]
### Version & browser
uiv 0.31.4 

Google Chrome | 72.0.3626.121 (Build ufficiale) (a 64 bit) (cohort: Stable)
Sistema operativo | Windows
JavaScript | V8 7.2.502.28

### Which component
[Multiselect] ([Dropdown])

### Steps to reproduce the problem
Clone latest repository

```
npm install

npm run dev
```

### Reproduce link
http://localhost:8080/multi-select

(local development server)

### Expected behavior
Clicking on item in the list, selecting the items the dropdown should remain active.

### Actual behavior
Clicking the item over the <span> node, the dowpdown disappear.

It seems that the problem affect version from 0.30.0, in the documentation public website the problem is not present.
https://uiv.wxsm.space/multi-select

Example:
![multiselect_dropdown](https://user-images.githubusercontent.com/2877000/54765661-32efe300-4bfa-11e9-86be-d2cf3e2ae491.gif)

**Comment by wxsms** [comment]
Thanks for the feedback. fixed now.

**Comment by etino** [comment]
You are welcome. Thank to you for this good project. 👏
