### ISSUE TITLE
Add custom classes for tab content

### ISSUE THREAD

**Issue by t0lik** [wxsms/uiv#279]
Please add an ability to indicate custom classes for a tab content in the Tabs component. This could be useful to tune up the tab content itself.

**Comment by wxsms** [comment]
you can add class to the child tag of each tab content, it's the same.

**Comment by t0lik** [comment]
In [this](https://jsfiddle.net/tn6ub0mg/) expample I cannot set height to 100% for tab-item div if I don't set tab-content to flex: 1.

**Comment by wxsms** [comment]
I see.
