### ISSUE TITLE
Focus issues when modal is open

### ISSUE THREAD

**Issue by skyrpex** [wxsms/uiv#28]
Bootstrap limits the focus to the items within the modals (no matter how many times you press tab, you'll only focus items inside the modal). I'm not sure about the implementation, but I was going to add it to my own library.

I could make a MR for this.

**Comment by wxsms** [comment]
OK, please go ahead.

**Comment by skyrpex** [comment]
Cool!

Just for reference: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/modal.js#L276-L286

**Comment by wxsms** [comment]
close due to no response, re-open if needed.
