### ISSUE TITLE
Keyboard typeahead selection causes form submit

### ISSUE THREAD

**Issue by tinyfly** [wxsms/uiv#281]
### Version & browser
uiv - 0.31.5
browser all

### Which component
Typeahead

### Steps to reproduce the problem
* Add a typeahead component to a form with an `@submit` handler
* Type in the typeahead target input to get some results
* Use the keyboard arrows to navigate the results and hit the enter key to select an item

### Reproduce link
https://codepen.io/tinyfly/pen/XwMNdW

### Expected behavior
Only a typeahead result is selected

### Actual behavior
Typeahead result is selected and the keydown event is fired on the target input causing the form submission.

Here is my use case. I quite often use the typeahead to have city completion in a form that has other input fields after the typeahead. Currently if I use the keyboard to select a result it'll also fire the enter keydown event and submit the form resulting in premature submission and validation errors. I think trapping the enter key with a preventDefault if the user is making a selection otherwise let it continue like normal would work. I tried to get around this whole thing by using some v-on listeners in various ways but nothing I tried would stop the enter key event without completely killing it all together.

Though I could see having the enter key select and submit the form useful if there is just the one typeahead input in the form. Sort of like google search where if you hit enter on one of their suggestions it'll select and submit the form.

So maybe having another prop to turn to enable this would be useful.

**Comment by tinyfly** [comment]
I kind of look at a typeahead field as similar to a browser's autocomplete suggestions. If you are filling out an email field and the **browser** suggests your email you can select it with the keyboard and hit the enter key and it just populates the field. It doesn't also submit the form.

**Comment by wxsms** [comment]
I simply added a `event.preventDefault()` to the enter key event, looks like it works as expect now.

**Comment by tinyfly** [comment]
Great thank you!
