### ISSUE TITLE
MultiSelect should not directly update the "value" prop

### ISSUE THREAD

**Issue by nsorin** [wxsms/uiv#283]
### Version & browser
Version 0.31.5, all browsers

### Which component
MultiSelect

### Expected behavior
The props should not be modified by the component and should only be used as they are provided by the parent. Updates should only come from events, which are then handled by the parent. In the case of _value_, the proper way to update it would be to make a copy, update the copy and send it back to the parent via the _input_ event.

### Actual behavior
When an option is selected, this.value is updated. This interferes with parent logic by updating one of its variables. From the source code:

```js
          if (index >= 0) {
            this.value.splice(index, 1)
            this.$emit('change', this.value)
          } else if (this.limit === 0 || this.value.length < this.limit) {
            this.value.push(value)
            this.$emit('change', this.value)
          }
```

**Comment by wxsms** [comment]
thanks for the feedback.
