### ISSUE TITLE
Modal closed when cursor is released outside the modal

### ISSUE THREAD

**Issue by gabrstomas** [wxsms/uiv#285]
I found on StackOverflow and Github that it is appearing after Google Chrome update. It is working well in Firefox. It is appearing when using combination Bootstrap 3.3.7 and Google Chrome 74.0.3729.169. Bootstrap developers said on [GitHub](https://github.com/twbs/bootstrap/issues/28844) that Bootstrap 3.3.7 is not maintained anymore and they are not planning to fix it. I am not sure if it will be fixed in Google Chrome update. We are using UIV library in our project and it would be great if modal could be fixed directly in the library, so we do not have to implement our own modal because this library is excellent!

Using backdrop is not a solution, because we want to close the modal after click outside.

### Version & browser
Google Chrome Version 74.0.3729.169

### Which component
Modal

### Steps to reproduce the problem
1. Click to the modal, hold the mouse button down, move outside of the modal and release button.
2. Select text in modal, but end your movement outside of the modal.

### Expected behavior
Modal is not closed

### Actual behavior
Modal is closed

**Comment by wxsms** [comment]
Thanks for the feedback, fixed now.

**Comment by wxsms** [comment]
Sry, I found that my solution is causing some unwanted side effects, I have to revert it and found another way to solve this. 😢
