### ISSUE TITLE
Detecting dropdown outside click

### ISSUE THREAD

**Issue by tinyfly** [wxsms/uiv#287]
I'm a little bit stumped. I've got a widget inside of a dropdown with a "Cancel" and an "Apply" button. When the dropdown is closed through a click outside of the dropdown itself (like say I clicked on a button elsewhere on the page), I want to trigger the "Cancel" action in the widget. I'm not sure how to do that though.

I can listen to the input event on the dropdown for true/false but I can differentiate the boolean that comes through that outside click from a manual change to the v-model that I do when the user clicks "Apply"

If you've got ideas on how to do this I'd appreciate it.

**Comment by tinyfly** [comment]
For clarification both cancel and apply set the v-model value to false to hide the dropdown. So I can't just listen to `@input` for false and trigger the cancel method.

**Comment by wxsms** [comment]
A work around is, make a flag that indicate if user has click `apply`, set it to `true` before hiding the dropdown. And watch the `v-modal` of dropdown as you said.

But it should be better with some event when outside click happened of cause.

**Comment by tinyfly** [comment]
@wxsms That makes perfect sense, I don't know why I didn't think about setting flags. Thanks
