### ISSUE TITLE
[Question] How I can add click-ouside listener to close a popover triggered manuallly?

### ISSUE THREAD

**Issue by etino** [wxsms/uiv#288]
I've trigged manually a popover using trigger="manual". 
The popover is opened inside a modal window, so when the user click outside, the modal close automatically but the popover remain open.

How can I manage the event to close also the popover opened?

This is my example code
```
<template>
  <section>
    <popover title="Title" trigger="manual" v-model="show">
    <template slot="popover">
        <p>Popover content</p>
        <btn type="primary" @click="show = false>Close Popover</btn>
      </template>
    </popover>
  </section>
</template>
<script>
  export default {
    data () {
      return {
        show: false
      }
    }
  }
</script>
```
The base script is pretty easy.

For understand better the problem, I attach an animated gif for the example.

Thank you for your help.

![popover_click_outside_event](https://user-images.githubusercontent.com/2877000/59703604-88885b80-91fa-11e9-9c6a-4d22d81d78ba.gif)

**Comment by wxsms** [comment]
Set `show` to false on modal `close` event.

**Comment by etino** [comment]
Thank you @wxsms.

You are right, I didn't think it.

Since in my case the event should be passed from parent to child, I've used a custom event on EventBus. 

This is my solution.

In my **main.js**
``` 
Vue.prototype.$bus = new Vue()
```

In my **Parent Component** (Modal)
```
  watch: {
    show(value) {
      this.$bus.$emit('EVT_MODAL_CLOSE', value)
    }, 
```
In my **Child Component** (Popover)

```
    mounted() {
        this.$bus.$on('EVT_MODAL_CLOSE', (event) => {
            this.show = event
        })
    }, 
```
