### ISSUE TITLE
Multi-Select border dose not expand in height

### ISSUE THREAD

**Issue by allan98** [wxsms/uiv#293]
### Version & browser
0.32.2/chrome 75

### Which component
muliti-select

### Steps to reproduce the problem
 when too many items selected

### Expected behavior
the border of muliti-select will be auto expanded in height

### Actual behavior

![图片](https://user-images.githubusercontent.com/18660781/60765906-017d2380-a0d4-11e9-9dc3-4df637c0773b.png)

**Comment by mortzion** [comment]
I found out that this is due to the fact that the wrapper has a form-control class, which sets height to 34px. You can quickfix this by applying height: auto to the wrapper.

**Comment by allan98** [comment]
Thanks, it works
