### ISSUE TITLE
Add support for Popover Class and Style Bindings

### ISSUE THREAD

**Issue by arrancardnell** [wxsms/uiv#294]
### Which component

Popover

### Steps to reproduce the problem

`<Popover :style="{'max-width': '100%'}">...</Popover>`

### Expected behavior

Popover style should have 'max-width'  property set to 100%.

### Actual behavior

Custom class and style bindings aren't applied to Popover. In cases where the Popover is moved to the HTML body, there is no way to uniquely style a Popover within a scoped custom VueJS component without overriding it globally (which is not desirable).

Suggest adding ability to bind custom class and styling to Popover components.

**Comment by alvarezmario** [comment]
I really need this! I'm having a big issue where I need to update the max-width of the popover and I can't do it without changing the global value.

**Comment by arrancardnell** [comment]
FYI @alvarezmario , if you want a workaround, you can add a ref to the Popover like this:

`<Popover ref="popover">...</Popover>`

...and then in your VueJS code you can access the popover and adjust the styling, such as:

`mounted: {
    this.$refs.popover.$refs.popup.style.maxWidth = '100%;
}`

Not an ideal solution, but it works!

**Comment by wxsms** [comment]
e79e88d0
