### ISSUE TITLE
Should have looser ESlint rule

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#3]
Trun Error to Warning

![image](https://cloud.githubusercontent.com/assets/15178410/24733687/a304b094-1aab-11e7-8e74-6f89b030b6cc.png)

**Comment by wxsms** [comment]
Sry, vue-cli is recommend  error level and I don't think lower it is a good idea. Strict ESLint helps project grow better.

**Comment by zcyzcy88** [comment]
OK, but now is [not pass lint -> can't run/test]
I think [not pass lint -> can't commit] will better
