### ISSUE TITLE
Hide navbar on clicking navlink in collapsed menu

### ISSUE THREAD

**Issue by sagar947** [wxsms/uiv#301]
### Version & browser
al

### Which component
Navbar

### Steps to reproduce the problem
Collapse the screen to a smaller size. Click on the menu collapse and then click on a nav link.

### Expected behavior
Need to hide the collapsed menu after the user clicks on the navlink

### Actual behavior
The collapsed menu stays open and the user has to click on the collapse menu button again to close the menu.

**Comment by wxsms** [comment]
Thanks for the comment, but this feature you mention was not in jQuery version of Bootstrap, to avoid confuse and keep the lib clean, it will not be implement here as well.

Instead, you can use `v-model` prop to control it's togging as you wish.

**Comment by sagar947** [comment]
Can you please elaborate what can be done with the `v-model` prop?

**Comment by wxsms** [comment]
you can set `v-model` value to false when use click navlink in your case.
