### ISSUE TITLE
The v-show directive doesn't work with tab component

### ISSUE THREAD

**Issue by tesicg** [wxsms/uiv#308]
Hello,

We've noticed that v-show directive didn't work with tab component. You can simply try:

`<tab v-show="false"...`

We really need this to be fixed.

Thank you in advance.

Goran

**Comment by wxsms** [comment]
Can you use `v-if`?

**Comment by wxsms** [comment]
closing due to no response

**Comment by t0lik** [comment]
No, we cannot use v-if because we need this tab and its content alive but not visible. Can you add an option to show/hide a certain tab reactively?

**Comment by wxsms** [comment]
@t0lik can you solve that with `keep-alive`?

**Comment by t0lik** [comment]
how exactly? Can you show an example on jsfiddle or codepen?

**Comment by wxsms** [comment]
Added a `hidden` prop to control this. pls try in next version.
