### ISSUE TITLE
v-scrollspy doesn't support dynamic arguments (element ids)

### ISSUE THREAD

**Issue by ventralnet** [wxsms/uiv#312]
Currently it looks like scrollspy doesn't support dynamic arguments
https://vuejs.org/v2/guide/custom-directive.html#Dynamic-Directive-Arguments

To reproduce
try to use a data, prop or computed property as the scroll-container arg and the scrollspy constructor will throw an error

Not sure if you were planning to support this or not, but figured I would log the issue anyways

**Comment by wxsms** [comment]
Thanks for reporting, I do not notice that there is a `dynamic args` yet, will have a learn and make this implemented.

**Comment by wxsms** [comment]
I can't see an error, it just won't work, anyway, fixed now. if any futher problems feel free to continue.
