### ISSUE TITLE
Tooltip directive runtime errors

### ISSUE THREAD

**Issue by rjregenold** [wxsms/uiv#314]
Hi,

Thank you for creating uiv. We use it extensively in our application. I've noticed a couple runtime errors in our logs and tracked them down to using the tooltip directive. They're pretty tricky to reproduce, but I believe they occur whenever the `popup` is modified before a `setTimeout` function that uses the `popup` is called. For example, if the tooltip is about to appear but the underlying component is updated at the same time, it will attempt to modify `this.$refs.popup` but it has been destroyed so is `undefined`.

I created a small, contrived example of this behavior here:

https://jsfiddle.net/yhe8akto/

If you open the dev console in Chrome or Firefox, then `mouseenter` and `mouseleave` over the "Hover over me." text, you will occasionally see the error.

I did my best to create tests that re-create this behavior and created a PR that resolves the issues. Please let me know if I need to change anything in the PR.

Thanks again for your great library.

**Comment by wxsms** [comment]
Thanks for the PR, merged now. It's very nice to have the unit tests implemented. 👍
