### ISSUE TITLE
MultiSelect: truncate long labels 

### ISSUE THREAD

**Issue by robwbruder** [wxsms/uiv#319]
When the selected option has a long label, the label wraps and overflows the container; this problem - and a potential solution - is demonstrated in [this example](https://codesandbox.io/s/uiv-multiselect-long-label-km3ni?file=/src/App.vue). Though this shouldn't be a problem in static pages, this is potentially a problem for dynamic options with labels of unknown length or for MultiSelect instances that adjust to the width of the browser window.

**Comment by wxsms** [comment]
thanks for your solution, pls try in next version.
