### ISSUE TITLE
Drag select possible on dropdown label

### ISSUE THREAD

**Issue by robvdl** [wxsms/uiv#322]
**Describe the bug**
When clicking on a dropdown menu if you accidentally drag select with  the mouse you are able to select text on the dropdown label. It's a very minor bug but just noticed it as I've just ported some code over from jquery based bootstrap.js to uiv and bootstrap.js didn't do that.

**Expected behavior**
Text selection should not be possible on the drop down menu label.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 81

**Comment by wxsms** [comment]
It's on your decision. If you don't want the drag select, add `href="#"` or `href="javascript:;"`  to your `<a>` tag inside dropdown slot. Same as the jq ver.

**Comment by robvdl** [comment]
Thank you, I didn't realise the href="#" did this. Awesome, learned something new today.

I thought the href="#" just affected how it rendered, it affects the CSS too.

Closing, not a bug.
