### ISSUE TITLE
Typeahead network

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#33]
Fast focus, fast typed, fast blur (blur when requesting), then the menu will show after blur.
![demo](https://cloud.githubusercontent.com/assets/15178410/25493199/ef71dec2-2ba7-11e7-8a22-9f081be7d5d9.gif)

You should abort requesting after blur (it is nasty for Promise without cancelToken) ,
or don't do `prepareItems` when blur.

**Comment by wxsms** [comment]
seems can't stop the promise
