### ISSUE TITLE
Scrolling modal dismisses modal

### ISSUE THREAD

**Issue by pdl** [wxsms/uiv#334]
**Describe the bug**
Using the scroll bar to scroll while a modal is active dismisses the modal

**To Reproduce**
1. Go to https://uiv.wxsm.space/modal
2. Click on 'Launch demo modal'. Note the presence of the contextual scrollbar at the right of the page (unless your screen is huge) instead of the page scrollbar.
3. mousedown on scrollbar in order to begin scrolling
4. Immediately the modal is dismissed with screen-corner alert info message "Modal dismissed with msg 'dismiss'."

**Expected behavior**
The modal should not be dismissed by mouse events on the scroll bar, and the scroll bar should be usable so that the user can access later parts of the modal.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  83.0.4103.116
(but I have reports of similar behaviour on mac and have no particular reason to think it is just chrome at the moment)

**Additional context**
I suspect (but have not tested) based on the changelog that this was introduced in v0.34.2.

**Comment by pdl** [comment]
I can reproduce in IE11 and Firefox 78 on Windows.

I have confirmed that the issue is not a problem for me in v0.34.1.

**Comment by wxsms** [comment]
Yes I confirmed this issue happends on Mac too.
