### ISSUE TITLE
Custom Typeahead

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#34]
### sub-header & footer

<img width="336" alt="2017-04-28 00_43_00- - - internet explorer" src="https://cloud.githubusercontent.com/assets/15178410/25494393/1a682268-2bac-11e7-8cb4-fb99d5cf1fae.png">

---

### show suggestions when empty

<img width="628" alt="2017-04-29 16_01_54-component _ element" src="https://cloud.githubusercontent.com/assets/15178410/25554003/4ebb2714-2cf5-11e7-9ede-e66e3083423f.png">

http://element.eleme.io/#/en-US/component/input#autocomplete

---

### show history when empty, show autocomplete when typed

<img width="204" alt="2017-04-28 00_18_32- - -bilibili" src="https://cloud.githubusercontent.com/assets/15178410/25494199/6f55527e-2bab-11e7-80e2-8ecebd4492f7.png">

<img width="204" alt="2017-04-28 00_33_38- - -bilibili" src="https://cloud.githubusercontent.com/assets/15178410/25494200/6fd5b702-2bab-11e7-9aa9-0328120809e8.png">

---

Is there any idea?

**Comment by wxsms** [comment]
> sub-header & footer

I can make the `item` slot bigger, which allow user to take full control of dropdown content.

> show suggestions when empty. show history when empty

How to achieve these?

* suggestions when empty: another prop for user?
* history: localstorage? cookie? indexdb?

> show autocomplete when typed.

Sry, I don't understand this. The Typeahead is doing autocomplete now. what's your point?

**Comment by zcyzcy88** [comment]
> - suggestions when empty: another prop for user?
Yes. 

---

> - history: localstorage? cookie? indexdb?

> show autocomplete when typed.

I mean combine local history & remote suggestions 

when empty -> show local data
when typed -> show remote data

**Comment by wxsms** [comment]
> I mean combine local history & remote suggestions

I can't get your point. If you still want this you can make a PR for it. I'm going to close this one. Thanks.
