### ISSUE TITLE
If two modals share the same v-if condition the calculated z-index is incorrect, resulting in popover misbehaviour.

### ISSUE THREAD

**Issue by StefanCardnell** [wxsms/uiv#342]
**Describe the bug**

If two modals share the same v-if condition, initially false and then becoming true, the z-index of the first modal will be too high. Popovers placed on the first modal will then not appear (due to their lower z-index).

This is also related to the ticket here: https://github.com/uiv-lib/uiv/issues/341 - if popovers respected modal z-index I don't think this would be an issue.

**To Reproduce**

Please see demonstrative example: 

https://codesandbox.io/s/uiv-bug-o5tyh?fontsize=14&hidenavigation=1&theme=dark

1) Two modals must be created and depend on the same v-if condition, initially false (`if_condition`)
2) The first modal must begin v-modelled on to a false variable (`v_model_a`)
3) A button must set the if condition and v-model attributes of the first Modal to true (`if_condition` and `v_model_a`).

When clicking "Open Modal" the popover inside the modal will not appear. If the modal is then closed and opened, it will appear.

**Additional context**

I have examined the UIV Modal code and understand the cause, but I cannot suggest the fix.

1) Inside Modal.vue, the function `getOpenModalNum` gets the number of open modals by checking how many `.modal-backdrop` elements exist in the DOM.
2) Inside the `$toggle()` method the z-index of the opening Modal is given an offset depending on how many modals are open.

But no modal was open when the Modal was opened and `$toggle()` was called, so why was the z-index offset? The answer is because:

3) In Modal.vue, the `.modal-backdrop` div initially exists in the template and is removed in `mounted()`.
4) Therefore in my example, as soon as the `v-if` condition becomes true, the `.modal-backdrop` for both modals are inserted in to the DOM - however `mounted()` is first called for Modal A and completes execution (opens the modal) before the `mounted()` is called for Modal B which would have removed its own `.modal-backdrop`. Therefore `getOpenModalNum` in `$toggle` on the first run for Modal A produces 1, as it detects the backdrop of Modal B.

You may find it strange that I am using both v-if and v-model for the modal, however I do this a lot over my project when the slotted contents of the modal require require an object not to be null. This object is tested in the v-if of the modal. 

You may say I should control the Modal slotted contents with a v-if. However I am often wrapping Modal in my own wrapper component that takes the object - and placing v-if on that wrapper instead, not the Modal. The wrapper expects that the object is non-null, as it often kicks off APIs on mounts and it would be more work to ensure the wrapper could handle null values.

**Workaround Found**:

Use `$this.nextTick` around the v-model attribute change. This allows both Modal's `mounted()` to run before displaying the first modal.

**Comment by wxsms** [comment]
I understand what you said. Thanks for the very clear description. I will find out a solution for this.

**Comment by wxsms** [comment]
@StefanCardnell pls try 0.36.1

**Comment by StefanCardnell** [comment]
Have tried 0.36.1 and the issue seems to be fixed. Thanks for the resolution @wxsms.
