### ISSUE TITLE
Allow `append-to` property of PopUp Mixins to pass `ref`

### ISSUE THREAD

**Issue by colinalford** [wxsms/uiv#347]
**Is your feature request related to a problem? Please describe.**
I often need to create popovers on lists of items for my application. the `append-to` prop only accepts strings, so I have to create unique identifiers for each DOM element where I want a popover to trigger.

**Describe the solution you'd like**
The `append-to` prop for popovers should be able to accept either an element reference or a string. If a string is passed, it would attempt to query for it. If an element is passed, it wouldn't need to do anything, since the element has been provided.

In my component, I already have access to this element, so it is much easier and more generic to pass a reference in rather than trying to generate unique strings in the DOM. It also eliminates the need for an additional query when I can provide the element to the popover.

**Describe alternatives you've considered**
The alternative is for me to generate unique IDs or high specific CSS selectors for each element whenever I need to use a popover on my list.

**Additional context**

**Comment by wxsms** [comment]
it's done, will be added in next version.
