### ISSUE TITLE
Pre-selected Option in Multiselect component [Question]

### ISSUE THREAD

**Issue by etino** [wxsms/uiv#373]
Hello, I need to preselect an option in a MultiSelect component.
Options have the following format
```
options: [ {label: "Label 1", value: Object1}, {label: 'Label 2: value: Object}, ...]
```

I've tried to put my preselected option in the `selection` binding array

```
this.selection.push(Object)
```

but the Multiselect display `[object Object]` value as Label.

Screenshot
![image](https://user-images.githubusercontent.com/2877000/96732319-7c954680-13b8-11eb-8fc6-1076026a8677.png)

How can I set correctly a pre-selected option? 

Thank you for your help

**Comment by wxsms** [comment]
You need to push the `value` into your selected array. If the value is an object, make sure that you're pushing the same reference of it.

Here is a demo: https://codepen.io/wxsm/pen/ZEOBLqK

**Comment by etino** [comment]
I confirm that's what I expected.
Thank you @wxsms :-)

**Comment by wxsms** [comment]
welcome.
