### ISSUE TITLE
DatePicker bound to object property does not update correctly

### ISSUE THREAD

**Issue by tech-no-logical** [wxsms/uiv#38]
I'm using multiple datepickers in dropdowns bound to object properties like in this gist

https://gist.github.com/tech-no-logical/de701dcaf992a384725f06d905a5e7ea

when using it as such, the bound model (and visually the input) updates one event late, like so

- select may 29th -> nothing happens
- select may 30th -> updates to may 29th
- select may 27th -> updates to may 30th

am I doing something wrong, or is this a bug ? I really need separate datepickers bound to dynamice properties...

**Comment by lp** [comment]
It looks like the example at [https://uiv.wxsm.space/date-picker](https://uiv.wxsm.space/date-picker) also offsets date displays.

![datepicker_offset](https://cloud.githubusercontent.com/assets/32278/26560977/a97bc028-4488-11e7-8f12-a779202b6056.jpeg)

In the example, I selected the 26th of May, 2 out of 3 displays are wrong when displaying it.

**Comment by tech-no-logical** [comment]
I can't reproduce that, but my problem isn' t an offset, it's that the model shows the _previously_ selected value instead of the _current_ one.. I probably could've worded that better...

**Comment by lp** [comment]
ok, I opened an other issue from my comment.  thanks!

**Comment by wxsms** [comment]
https://vuejs.org/v2/api/#v-for

If you want to bind v-model to an object prop, you should do this:

```
v-for="(val, key) in object"
```

And use it with v-model like this:

```
v-model="object[key]"
```

Then your case should work (tested).

**Comment by tech-no-logical** [comment]
thanks. it seems that, in combination with your solution, I also did something funky with the object in question in the create() method causing some properties not to be reactive. everything works as advertised now :)

thanks !
