### ISSUE TITLE
Display Offset

### ISSUE THREAD

**Issue by lp** [wxsms/uiv#39]
It looks like the example at [https://uiv.wxsm.space/date-picker](https://uiv.wxsm.space/date-picker) offsets date displays.  I get the same bug when using it within my own code.

![datepicker_offset](https://cloud.githubusercontent.com/assets/32278/26561888/e6c7f724-448f-11e7-91ea-7a373765f945.jpeg)

In the example, I selected the 26th of May, 2 out of 3 displays are wrong when displaying it.

**Comment by wxsms** [comment]
Strange. How do you get this result? Click on the datepicker or change the value in text input? I can't reproduce it.

**Comment by wxsms** [comment]
Closing since no response. re-open this if need. thanks.
