### ISSUE TITLE
IE 11 Foreach error

### ISSUE THREAD

**Issue by Tronhus** [wxsms/uiv#395]
**Describe the bug**
IE11 bug when using a modal. When the modal er removed from the view it calls toggleBodyOverflow function in file dom.utils.js 
The code uses Foreach on a list of html elements line 340 and 349. The foreach breaks in IE 11 
A possible solution could be https://rimdev.io/foreach-for-ie-11/

**To Reproduce**
in IE 
add a modal to page
close modal on page,

**Screenshots**
![2020-11-17 09_14_14-](https://user-images.githubusercontent.com/1876819/99363818-7e6a0100-28b5-11eb-9535-c2b240499837.png)
![2020-11-17 09_14_32-](https://user-images.githubusercontent.com/1876819/99363837-83c74b80-28b5-11eb-95ea-1fe61ae37b67.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser IE
 - Version 11

**Comment by wxsms** [comment]
Nice catch. fixed in 1.1.5
