### ISSUE TITLE
Modal backdrop child elements click issue

### ISSUE THREAD

**Issue by agustin-tiendanube** [wxsms/uiv#40]
When an element that was conditionally rendered (using v-if, not v-show) is clicked, the modal is closed.

I think is because of [this condition in Modal.vue](https://github.com/wxsms/uiv/blob/master/src/components/modal/Modal.vue#L169):
```
    backdropClicked (event) {
        if (this.backdrop && !this.$refs.dialog.contains(event.target)) {
          this.toggle(false)
        }
      }
```

I have a fix for it, I can create a PR.

**Comment by wxsms** [comment]
Pls paste your code.

**Comment by agustin-tiendanube** [comment]
You have a click handler in the modal div:
```
[...]
    <div ref="backdrop" class="modal-backdrop" :class="{fade:transitionDuration>0}"></div>
    <div ref="modal"
         class="modal"
         :class="{fade:transitionDuration>0}"
         tabindex="-1"
         role="dialog"
         @click="backdropClicked"> <!-- THIS HANDLER -->
      <div ref="dialog" class="modal-dialog" :class="modalSizeClass" role="document">
[...]
```
And in the handler:
```
      backdropClicked (event) {
        if (this.backdrop && !this.$refs.dialog.contains(event.target)) {
          this.toggle(false)
        }
      }
```

The problem happens with elements inside the modal that wasn't render on the modal creation (for example, a button that only shows up when a condition is met):

```
<modal>
    <button v-if="someConditionThatIsFalseOnMount" @click="doSomething">
</modal>
```

When that button appears and is clicked, the condition `!this.$refs.dialog.contains(event.target)` still returns true, so the `toggle` functions is still being called.

To prevent this I added a @click.stop in the `modal-dialog`:

```
[...]
    <div ref="modal"
         class="modal"
         :class="{fade:transitionDuration>0}"
         tabindex="-1"
         role="dialog"
         @click="backdropClicked"> <!-- THIS HANDLER -->
      <div ref="dialog" class="modal-dialog" :class="modalSizeClass" role="document" @click.stop>
[...]
```

Sorry for my bad english! :)

**Comment by wxsms** [comment]
@agustin-tiendanube I see. this only happens when the button action set its `v-if` to false.

However, `@click.stop` on dialog is not a solution to this since some component may rely on window click event to show/hide.

Just add a commit to this issue. should solve the problem and will release on next version.
