### ISSUE TITLE
Datepicker not parsing correctly with some format

### ISSUE THREAD

**Issue by tech-no-logical** [wxsms/uiv#42]
hi,

I've run into an issue with the format support in the datepicker. I want (or need) to use 'dd-mm-yyyy' as a format (used in some countries, notably the netherlands), but since this is not supported by js's Date.parse() call, this fails horribly. 

I've been testing with adding moment.js to parse and format dates, and this seems to work fine so far. however, adding moment.js also allows the easy internationalization of the calendar, which conflicts with the efforts to add i18n to uiv.

is it a good idea to combine these efforts ?

**Comment by wxsms** [comment]
Hi, you can simply parse `dd-MM-yyyy` to the datepicker then it should work.

```
return format
        .replace(/yyyy/g, year)
        .replace(/MMMM/g, monthName)
        .replace(/MMM/g, monthName.substring(0, 3))
        .replace(/MM/g, stringUtils.pad(month, 2))
        .replace(/dd/g, stringUtils.pad(day, 2))
        .replace(/yy/g, year)
        .replace(/M(?!a)/g, month)
        .replace(/d/g, day)
```

**Comment by tech-no-logical** [comment]
that won't work. suppose I do 06-08-2017 (6th of august). if you do Date.parse() on that value, you get the 8th of june. so it only works one way...

**Comment by wxsms** [comment]
ok. I see.

1. I think this is a bug. I will try fix it.
2. No need for Momentjs.

**Comment by tech-no-logical** [comment]
if you want to fix it yourself, you need a custom parser to replace the Date.parse() call. there are some parsers around. I'll see what you come up with ;)

**Comment by wxsms** [comment]
Please read the `DatePickerDoc.vue` to findout the solution. I just tested and it should work. Thanks.

**Comment by tech-no-logical** [comment]
that look doable, thx :) I'll test it with the next release, we're now in testing phase so I don't want to change it right away.

**Comment by klubov** [comment]
Looks like it is still doesn't work as it should.

Format: dd.MM.yyy
Select date: 01.09.2018 (September, 1st)

Open calendar again, date: January, 9th

**Comment by wxsms** [comment]
@klubov you should use `dateParser` prop to support such format.
