### ISSUE TITLE
Badge color not working inside active Tab title slot

### ISSUE THREAD

**Issue by arrancardnell** [wxsms/uiv#437]
### Version & browser

uiv 1.2.1
Firefox 84.0.2 (64-bit)

### Which component

Tab

### Steps to reproduce the problem

Using a Tab with html-title and a backstring HTML string as follows:

```html
    <Tab>
      <template slot="title">
        <i class="fa fa-fw fa-filter"></i> Filters
        <span class="badge">5</span>
      </template>
    </Tab>
```

### Expected behavior

Badge inside an active tab should have a white background with tab color text as detailed in the docs [here](https://getbootstrap.com/docs/3.4/components/#adapts-to-active-nav-states)

![image](https://user-images.githubusercontent.com/6402515/54393866-34258b00-46a3-11e9-994c-2b1ce76595af.png)

### Actual behavior

Badge still has grey background even with active tab. 

![uiv-github-bug](https://user-images.githubusercontent.com/6402515/105993550-76d98c00-609e-11eb-8461-a45ea15ff21b.png)

This seems to be because the content of the tab link is wrapped in a div (vue-portal-target) element. 

![uiv-github-bug-2](https://user-images.githubusercontent.com/6402515/105993772-adafa200-609e-11eb-9876-b8f592e25437.png)

Moving the contents out of the div fixes the issue.

Issue seems related to a previous one: 276

**Comment by wxsms** [comment]
this div can only be removed while it has one single child node. this might be a limitation of vue 2. Extend bootstrap css to make the child selector not so strict to direct children might be a good work accound for now. Do you have any suggeustions?

**Comment by wxsms** [comment]
Nevermind. already found a solution.
