### ISSUE TITLE
DatePicker demo highlights wrong day

### ISSUE THREAD

**Issue by woodlandhunter** [wxsms/uiv#45]
When you click on a day on the inline datepicker demo the previous day is highlighted.

The input shows the correct date, but the alert below it shows the previous day as well.

![image](https://user-images.githubusercontent.com/6824706/27916413-9559e778-622e-11e7-8f87-30e08a06e8b6.png)

**Comment by zcyzcy88** [comment]
> When you click on a day on the inline datepicker demo the previous day is highlighted.

This is today.

**Comment by woodlandhunter** [comment]
@zcyzcy88 I clicked on the "Today" button so 7/5 should not be highlighted. Try it on another day if that helps you understand:

Click on any day: https://uiv.wxsm.space/date-picker

Thanks

**Comment by wxsms** [comment]
seems the same with #39 

@woodlandhunter what timezone are you in pls?

**Comment by woodlandhunter** [comment]
@wxsms I'm the US central timezone (UTC-06:00)

**Comment by wxsms** [comment]
v0.11.6 solved this. thanks.
