### ISSUE TITLE
No CSS styling on components

### ISSUE THREAD

**Issue by adilhz** [wxsms/uiv#46]
Hi,
I'm using the latest version of uiv
`
"uiv": "^0.11.5"
`
but for some reason, it's not loading any CSS stylesheets. I'm importing it like so (in my ConfigPanel.vue component):
```
import * as uiv from 'uiv';
components: {
    Tabs: uiv.Tabs, Tab: uiv.Tab
}
```

The tabs _work_ (I can switch between them), but they have no styling. Any suggestions?

Thanks

**Comment by wxsms** [comment]
Have you import bootstrap css into you page? If yes, pls try 0.11.4 to see if the older version works.

**Comment by adilhz** [comment]
Yep, same issue as before. However if I include `<link>` tags in my `index.html` file, it works - solution for now

**Comment by wxsms** [comment]
Tabs component has no style, all from bootstrap.

**Comment by adilhz** [comment]
The issue must be with importing bootstrap then. Solved the issue, thanks for the help!
