### ISSUE TITLE
Scrollspy initially always highlights the last section (regression)

### ISSUE THREAD

**Issue by ventralnet** [wxsms/uiv#467]
I performed a major upgrade from uiv@0.34.3 to uiv@1.2.1 and scrollspy seems to have a bug.  I have modals with a navigation on the left and scroll (spied) content on the right.  When I open a modal the last element in the nav list will be highlighted even though you are in the first section of the spied content.  If you scroll just a tiny bit scrollspy will start working again and the first section in the nav list will be highlighted.  I have confirmed that v0.34.3 scrollspy works as expected but in v1.2.1 it performs as I have described

**Comment by ventralnet** [comment]
I seem to have gotten around this by initializing my navigation section on nextTick when the modal opens (so the spy content has loaded I presume).  You can close this if you want unless you still deem it a bug

**Comment by wxsms** [comment]
Could you provide a minimal reproduce with codepen or something? that will be helpful.

**Comment by wxsms** [comment]
closing due to no response. thanks.
