### ISSUE TITLE
Can't use special characters with typeahead

### ISSUE THREAD

**Issue by AdrianLungu** [wxsms/uiv#50]
### OS, browser, uiv version
Mac OS X 10.12.5, Chrome 60, uiv 0.11.6

### Which component
Typeahead

### Steps to reproduce the problem
Use a special character (*, ?) in the typeahead input

### Expected behavior
Show strings that start with or contain the characters

### Actual behavior
```
[Vue warn]: Error in render function: "SyntaxError: Invalid regular expression: /*/: Nothing to repeat"
found in
---> <Typeahead>
```

**Comment by AdrianLungu** [comment]
I've currently fixed it in a fork by modifying the Highlight function in Typeahead.vue to:

```
highlight (item) {
        let value = this.itemKey ? item[this.itemKey] : item
        let inputValue = this.inputEl.value.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&')
        return value.replace(new RegExp(`${inputValue}`, this.regexOptions), '<b>$&</b>')
      }
```

**Comment by wxsms** [comment]
hi, sry for the late.

Thanks for you solution, if it works as expect, it's welcome to PR this.
