### ISSUE TITLE
Typeahead

### ISSUE THREAD

**Issue by vamfixed** [wxsms/uiv#517]
Is there an event "onSelectedItemChange"?

**Comment by wxsms** [comment]
![image](https://user-images.githubusercontent.com/5960988/116647130-693ce680-a9ac-11eb-83b3-08cf02a58c24.png)

Sounds the same as `input`?

**Comment by vamfixed** [comment]
I mean, when i use arrow keys up and down. I need to get the event. @input only triggers when i click the item or hit the enter key.

**Comment by wxsms** [comment]
since the `<input >` tag is control by yourself, you can simply add `@keydown` to your input box and do what ever you want.

**Comment by wxsms** [comment]
added an event
