### ISSUE TITLE
modal background is black 

### ISSUE THREAD

**Issue by romangutkin** [wxsms/uiv#52]
### OS, browser, uiv version
windows 10, uiv V0.11.6

### Which component
Modal

### Expected behavior
background has opacity when modal is shown. 

### Actual behavior
background is solid black when modal is shown.

**Comment by wxsms** [comment]
![image](https://user-images.githubusercontent.com/5960988/28813148-a167c2d2-76ca-11e7-9b44-e5a9fa9ac0f8.png)

what browser you use?

**Comment by romangutkin** [comment]
Chrome

**Comment by wxsms** [comment]
Modal has NO css defined. Therefore, this lib should not be the cause of your problem. I suggest you to check the `bootstrap.css` you imported, or check which style override the `modal-backdrop` class.

**Comment by wxsms** [comment]
Closing due to not a problem of uiv. If you found anything intrest, re-open it pls.
