### ISSUE TITLE
Implement "pull-right" for Tabs

### ISSUE THREAD

**Issue by HendrikJan** [wxsms/uiv#53]
This is actually a feature-request. I hope it is possible to implement it, but I understand that a lot of work goes into making a great library and there might not be time to implement this.

### OS, browser, uiv version
Windows 10, All browsers, uiv 0.11.6

### Which component
Tab(s)

### Steps to reproduce the problem
Try to create multiple tabs, and give one title class="pull-right" to try to make it appear at the right side of the Tabs.

    <tab title='This title should appear on the right' class="pull-right">
            Test Content
    </tab>

### Expected behavior
The tab should appear on the right side of the tabs bar

### Actual behavior
The tab appears on the left side of the babs bar and there is no way to make it appear on the right

**Comment by wxsms** [comment]
You will be able to do this on next release, thanks for you support to making this lib better.

**Comment by HendrikJan** [comment]
Thank you.
I found the following workaround in the current version, using JQuery:

    mounted: function(){

        Vue.nextTick(function(){

            $('.title-pull-right').closest('li').addClass('pull-right');

        });

    }

And HTML:

    <tab :html-title="true" title='<span class="glyphicon glyphicon-time title-pull-right"></span> Logs'>
        tab contents
    </tab>
