### ISSUE TITLE
Datepicker: "weekStartsWith" Option missing

### ISSUE THREAD

**Issue by werkzeugh** [wxsms/uiv#54]
the datepicker supports i18n, which is fine,
but i'm missing an Option to define wether to start a Week on Sunday or Monday.

**Comment by frohikey** [comment]
Yeah, I need this feature badly as @werkzeugh. So I implemented it and sent PR :)

**Comment by wxsms** [comment]
@frohikey Pls find my fix commit. it can help you fix bugs in your PR.
