### ISSUE TITLE
Changing contents of src/components

### ISSUE THREAD

**Issue by Mahan-F** [wxsms/uiv#58]
### OS, browser, uiv version
0.11.8

### Question
I've done some changes to the Modal.vue and some other components but they are not working on my page. I believe I have to rebuild the package with the changes or something similar but I am very new to this so not sure how to make it work. I would appreciate any help!

I am aware that if I make changes to them they will be overwritten once I update uiv but I plan to do some enhancements and when I see they are worthy I would make a pull request to add them to uiv.

**Comment by wxsms** [comment]
`npm run build`

**Comment by Mahan-F** [comment]
I have already tried that. Do I run it in the uiv directory or my project directory?

I ran it in uiv directory and I got an error saying something about build/build.js not existing.
Ran it in project folder it ran successfully but the changes were still not showing.

**Comment by wxsms** [comment]
You need to clone this repo, make changes, then build js file for use

**Comment by wxsms** [comment]
Closing due to not a valid issue
