### ISSUE TITLE
Resetting Typeahead

### ISSUE THREAD

**Issue by troygilbert** [wxsms/uiv#59]
Perhaps I'm just using the component incorrectly, but I'm needing to reset the Typeahead component to a blank input, but when I clear/null/empty the model the component is bound to nothing changes. I'm binding with `v-model` on the `<typeahead>` element. The model updates correctly when I interact with the typeahead, but when I interact with the model directly the Typeahead component is unaffected. I would have expected this binding to be two-way, am I incorrect?

**Comment by wxsms** [comment]
Hi there.
Yes it shall be 2-way, but for now it is not. I will try to enhance this.
For a workaround, you can simply set the model,and set the value of the input element too, then it should work as expect.

**Comment by wxsms** [comment]
Will be available on next release.
