### ISSUE TITLE
Ability to change the contents in modal header

### ISSUE THREAD

**Issue by Mahan-F** [wxsms/uiv#60]
Can we have a slot for the modal header itself not just the title so that we can also change the `x` button.

I am using uiv modals with forms inside of them and I want to have the `x` be cancelled with Vue when the forms are saving.

This is what I am doing right now for the buttons in the footer and i'd like to do the same for the header.

```
<template slot="footer">
    <button type="button" class="btn btn-default" :disabled="isSaving" @click="discardEdit"><span>Cancel</span></button>
    <button type="button" data-action="auto-focus" class="btn btn-primary" :disabled="isSaving" @click="save"><span v-if="!isSaving">Save changes</span><i v-else="isSaving" class="fa fa-pulse fa-spinner" aria-hidden="true"></i></button>
</template>
```

I tried doing this myself to create a pull request but I was having issues getting it to work hence why i'm creating this issue.

**Comment by wxsms** [comment]
Will be available on next release.
