### ISSUE TITLE
Feature request: Add custom size to modal

### ISSUE THREAD

**Issue by toreba** [wxsms/uiv#62]
I would like to write

`<modal size="my-size" ...>`

and get

`<div role="document" class="modal-dialog modal-my-size">... </div>
`

This can be done by changing Modal.vue:98 (not tetsted)
`computed: {
      modalSizeClass () {
        return 'modal-' + this.size
      }`

### Which component
Modal

**Comment by wxsms** [comment]
Pls ref to #43

**Comment by toreba** [comment]
Thanks. This solved my problem
