### ISSUE TITLE
Initial current month is incorrect when value from v-model is already set

### ISSUE THREAD

**Issue by isometriq** [wxsms/uiv#64]
### OS, browser, uiv version
Windows 10
Chrome 60
uiv 0.11.9

### Which component
DatePicker

### Steps to reproduce the problem
1. Use datepicker inside a dropdown like in the docs
2. Set the v-model to a predefined value, ie
```
//...
<date-picker v-model="date"></date-picker>
//...
data: ()=({
    date: '2017-08-25'
})
```

### Expected behavior
When opening the dropdown, expecting currentMonth to be set to 8 (august).

### Actual behavior
`currentMonth` is set to current date's, which is 9 (september) ..as I type now.

I've checked the source code. It seems that `currentMonth` and `currentYear` is set when component is `mounted`. I see that there is a `watch` for the `value`. However, I suspect that the hook will not be called until data changes.

I could use `computed` to make use of reactive value
```
computed: {
   dateValue: {
      get() {
        let ts = this.dateParser(val)
        if (!isNaN(ts)) {
          let date = new Date(ts)
          if (date.getHours() !== 0) {
            date = new Date(ts + date.getTimezoneOffset() * 60 * 1000)
          }
          return date;
        }
        return this.now;
      }
      set() {
          if (this.limit && ((this.limit.from && date < this.limit.from) || (this.limit.to && date >= this.limit.to))) 
          {
            this.$emit('input', oldVal || '')
          } else {
            this.currentMonth = this.date.getMonth()
            this.currentYear = this.date.getFullYear()
          }
      }
   }
}
```

**Comment by isometriq** [comment]
...or easier you could set `currentMonth` in `mounted` based on `this.value`

**Comment by isometriq** [comment]
tested and I confirm `watch` hook is only called when data changes, not on init

**Comment by wxsms** [comment]
Thanks for the bug report. Will be fixed in next release.
