### ISSUE TITLE
Enhance the Auto Adjust Placement option

### ISSUE THREAD

**Issue by francoismassart** [wxsms/uiv#67]
### OS, browser, uiv version
macOS Sierra v10.12.6
Firefox, Mobile Safari
uiv v0.11.9

### Which component
Popover

### Steps to reproduce the problem
- Visit the popover component page in the documentation with a small screen/width (320px)
- Click on the button to toggle the "Dynamic Popover"

### Expected behavior
I was expecting to see the entire popover content with the Auto Adjust Placement enabled.

### Actual behavior
Part of the popover is hidden. This is due to the fact that only four placements options are supported: `top`, `right`, `left`, `bottom`.

### Possible enhancement
Add support for additional placement options like on the [Popover x plugin](http://plugins.krajee.com/popover-x/demo#basic-usage)...

- Top Left
- Top Right
- Bottom Left
- Bottom Right
- Right Top
- Right Bottom
- Left Top
- Left Bottom

Use these new placement options automatically when Auto Adjust Placement is enabled.

**Comment by wxsms** [comment]
Hi there.

> Add support for additional placement options like on the Popover x plugin...

You example is using Bootstrap 4, not 3. And in Bootstrap 3 **there are no placement style classes such as `top-left` for popover**. So this is not easy to reach.

I just refine the auto placement algorithm, it should work better with top / right / bottom / left now.

I am closing this thread. If you have any better idea for this, you can reopen it. Thanks.
