### ISSUE TITLE
Tabs section class

### ISSUE THREAD

**Issue by AdrianLungu** [wxsms/uiv#70]
### OS, browser, uiv version
uiv 0.11.8

### Which component
Tabs

### Improvement
Could we add a class prop to the **Tabs** component on **section**? I have quite a few themes which define a class for the parent of **ul** (in this case **section**) and having the ability to define a custom class for it would be really helpful.

Thanks!

**Comment by wxsms** [comment]
Pls ref to #43

**Comment by AdrianLungu** [comment]
That works great, thanks!
