### ISSUE TITLE
vue i18n warnings

### ISSUE THREAD

**Issue by javialon26** [wxsms/uiv#72]
### OS, browser, uiv version
elementary os (ubuntu 16.04), chrome, uiv version 0.11.10

### Which component
modal

### Steps to reproduce the problem
use modal component with nuxt and vue i18n plugin and in terminal and in browser console show this warnings:

[vue-i18n] Value of key 'uiv.modal.cancel' is not a string!
[vue-i18n] Value of key 'uiv.modal.cancel' is not a string!
[vue-i18n] Cannot translate the value of keypath 'uiv.modal.cancel'. Use the value of keypath as default.
[vue-i18n] Value of key 'uiv.modal.ok' is not a string!
[vue-i18n] Value of key 'uiv.modal.ok' is not a string!
[vue-i18n] Cannot translate the value of keypath 'uiv.modal.ok'. Use the value of keypath as default.

component template:
```
<template lang="pug">
  modal(v-model="isOpen")
    cm-header-modal(slot="header", :title="title", @close="close")

    cm-login-form(v-show="form === 1", :reset-data="isOpen", @change-form="changeForm", @success="close")
    cm-reset-password-form(v-show="form === 2", :reset-data="isOpen", @change-form="changeForm")
    cm-register(v-show="form === 3", :reset-data="isOpen", @change-form="changeForm", @success="close")
    cm-register-form(v-show="form === 4", :reset-data="isOpen", @success="close")

    template(slot="footer")
      .row
        .col-xs-12
          span.text-center.legal-login Test
</template>
```

### Expected behavior
no warnings

**Comment by wxsms** [comment]
Have you merge the language pack of this lib to your app's?

**Comment by javialon26** [comment]
that was the problem, my app use spanish lang and in uiv is not defined. thank you!
