### ISSUE TITLE
generate modals dynamically in v-for loop

### ISSUE THREAD

**Issue by mware** [wxsms/uiv#73]
I hope someone can help. I'm trying to dynamically create a series of modal links and windows but I can only get the modal to work when using static names, ids and v-models names.

### OS, browser, uiv version
0.11.9

### Which component
modal

### Steps to reproduce the problem
in a v-for loop, need to use a variable to name the modal v-modal and match the trigger to open the modal

```
<a href="/#" role="link" :id="partner.partner_name" class="lender-select__modal-link" @click.prevent="partner.partner_name === true"><img :alt="partner.partner_name" class="lender-logo img-responsive" src="/static/img/lenders/whatever.jpg"></a>
<!-- Modal -->
<modal v-model="partner.partner_name" :aria-labelledby="partner.partner_name" size="lg" :header="false" role="dialog" :ref="partner.partner_name" aria-modal="true" title="Lender 1" tabindex="-1">
```

### Expected behavior
modal to work as it does in your demo

### Actual behavior
all modals open on page load, won't reopen after being closed.

**Comment by wxsms** [comment]
Pls ref to #38 , it should solve your problem.
