### ISSUE TITLE
ProgressBar/ProgressBarStack display crazy float numbers in label for some progress values

### ISSUE THREAD

**Issue by tgies** [wxsms/uiv#75]
### OS, browser, uiv version
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3230.0 Safari/537.36"

master (`23ec068`)

### Which component
`ProgressBar`, `ProgressBarStacked`

### Steps to reproduce the problem
With `<progress-bar v-model="foo">`, with the default `min` value of 0 and `max` value of `100`, if (for instance) `foo == 7`, the ProgressBar label will display "7.000000000000001%". This sort of thing happens for several other integers in 0..100 too. This of course causes the label to grow much wider for an instant and produces an unpleasant visual disruption.

### Expected behavior
The ProgressBar label should keep the same precision through the whole range of progress values.

### Actual behavior
The ProgressBar label displays numbers with several extra decimal places for certain progress values, due to the nature of floating point numbers.

**Comment by tgies** [comment]
This is because of the expression used here to derive a percentage based on value, min and max.

https://github.com/wxsms/uiv/blob/23ec068b39cf81edc03342abf2dabe34dcf2ad3d/src/components/progressbar/ProgressBarStack.vue#L55

I'm thinking the thing to do might be to slap a `Math.round()` around that.

**Comment by tgies** [comment]
Put in PR #76 to do just that.

**Comment by wxsms** [comment]
Thanks for your contribute!
