### ISSUE TITLE
Modal center

### ISSUE THREAD

**Issue by Xu-Li-Min** [wxsms/uiv#757]
Can add the modal centering setting?
This problem has been bothering me for a long time,
I use Vue2, can i update uiv v0 to v1?
Thanks

**Comment by wxsms** [comment]
You may use 1.x of uiv for Vue 2.

As for "modal centering setting", I don't understand. Can you provide more information?

**Comment by Xu-Li-Min** [comment]
> You may use 1.x of uiv for Vue 2.
> 
> As for "modal centering setting", I don't understand. Can you provide more information?

Thank You, I will use v1.x.

The current modal component appears at the top, I hope it has settings to make it appear in the middle.

**Comment by wxsms** [comment]
You may checkout if Bootstrap v3 has any option/styling to make it middle. This lib is aim for behave the same as the jQuery version of Bootstrap v3.

**Comment by Xu-Li-Min** [comment]
> You may checkout if Bootstrap v3 has any option/styling to make it middle. This lib is aim for behave the same as the jQuery version of Bootstrap v3.

Well.. it looks like Bootstrap 3 doesn't have a centering setting...
Thank you for your answer.

**Comment by wxsms** [comment]
Welcome.
