### ISSUE TITLE
Typeahead- Disable local filtering for Ajax calls to remote data sources

### ISSUE THREAD

**Issue by sgwdc** [wxsms/uiv#77]
When using the Typeahead component with Ajax calls to remote API's (instead of a local data source), it would be great if we could (by default) disable any local filtering out of the results.  The reason is because filtering is already being done remotely on the server side by API's that are able to be more forgiving about punctuation, abbreviations, spacing, etc.  For example with address geocoders, there are many different ways of writing the same address, and we need the Typeahead component to display all results returned in the Ajax call.****

**Comment by wxsms** [comment]
Yes I see the problem. Thanks for you suggestion.

**Comment by wxsms** [comment]
Will apply on next release.
