### ISSUE TITLE
something error : import locale from 'uiv/src/locale/lang/zh-CN'

### ISSUE THREAD

**Issue by allan98** [wxsms/uiv#779]
**Describe the bug**
In vite3.09/vue3.2.38/uiv2.04, when import locale from 'uiv/src/locale/lang/zh-CN', something error: [plugin:vite:import-analysis] Missing "./src/locale/lang/zh-CN" export in "uiv" package.

anyone help, thanks

**Screenshots**
![Snipaste_2022-11-14_15-14-01](https://user-images.githubusercontent.com/18660781/201597868-b0323c66-de9a-44dc-8d32-38c16cf978c8.png)

**Desktop (please complete the following information):**
 - OS: [win11]
 - Browser [chrome107.0.5304.107 64bit]

**Comment by allan98** [comment]
copy zh-CN to src directory，its done

**Comment by wxsms** [comment]
might be a vite bug I think? since the file should exist in that directory.
