### ISSUE TITLE
Notifications overlap each other

### ISSUE THREAD

**Issue by markgajdosik** [wxsms/uiv#789]
Hello! Just started migrating from uiv 1.x to 2.x when I noticed that toast notifications overlap at each placement. This is on the current latest (2.0.4). It is also happening in the docs: [https://uiv.wxsm.space/components/notification.html](https://uiv.wxsm.space/components/notification.html)

**Comment by wxsms** [comment]
It's a production-only problem. pls try latest version later.

**Comment by markgajdosik** [comment]
Thank you!
