### ISSUE TITLE
Initialize bootstrap-select.js inside popover

### ISSUE THREAD

**Issue by MoraesGil** [wxsms/uiv#79]
### OS, browser, uiv version
 Mac, Crhome , "uiv": "^0.11.10",

### Which component
bootstrap-select 
https://silviomoreto.github.io/bootstrap-select/

### Steps to reproduce the problem
i initialize my select picker by mounted method but this don't trigger until Popver First open
i guess popver not render slot until first trigger
can anyone help?

> mounted() {
    $('.selectpicker').selectpicker({
      style: 'btn-info',
      size: 4
    });
    
  },

```
<popover title="Filtro avançado" placement="bottom" trigger="click" @show="bindThird" >
                    <a href="#" class="custom-btn" @click.prevent data-role="trigger">
                      <i class="fa fa-filter" aria-hidden="true"></i>
                      make filter
                    </a>
                    <div slot="popover">
                     
                      <select class="selectpicker" multiple title="Filte por categorias">
                        <option>Ketchup</option>
                        <option>Relish</option>
                        <option>Mustard</option>
                        <option>Ketchup</option>
                        <option>Relish</option>
                        <option>Mustard</option>
                        <option>Ketchup</option>
                        <option>Relish</option>
                      </select>
                      <br><br>
                      <button type="button" class="btn btn-default btn-block" @click="applyFilters" trigger="click">
                        apply filter
                      </button>
                    </div>
                  </popover>
```

### Expected behavior
<img width="274" alt="captura de tela 2017-10-10 as 20 03 13" src="https://user-images.githubusercontent.com/7747175/31414842-329d0494-adf6-11e7-8896-5a862720a5d1.png">

### Actual behavior
<img width="248" alt="captura de tela 2017-10-10 as 20 05 51" src="https://user-images.githubusercontent.com/7747175/31414908-91d6d4d0-adf6-11e7-8b92-8c0994f7cdb8.png">

**Comment by wxsms** [comment]
> i guess popver not render slot until first trigger

Yes.

So you can't do `$('.selectpicker').selectpicker` on `mounted` because the HTML element is not actually exist. You have to do this after the element had been inserted.

For example, use the `show` event on popover component.
