### ISSUE TITLE
Btn component uses RouterLink component that is missing

### ISSUE THREAD

**Issue by sjrd218** [wxsms/uiv#803]
**Describe the bug**
I am using the Btn component in a Vue3 app that doesn't use VueRouter and I get the following error in the dev console:
`[Vue warn]: Failed to resolve component: RouterLink`

**To Reproduce**
Create a Vue 3 app that uses uiv and use a Btn component in your template.

**Expected behavior**
Btn component doesn't have a dependency on VueRouter

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser chrome with Vue dev tools
 - Version 112

**Comment by wxsms** [comment]
fixed in 2.0.6
