### ISSUE TITLE
XSS Vulnerability on Tooltip

### ISSUE THREAD

**Issue by sdrioux** [wxsms/uiv#804]
**Describe the bug**

On 1.x, implementing a Tooltip results in a XSS vulnerability.  If a tooltips text is dynamic, it is possible to execute a script when the tooltip loads.

**To Reproduce**

Create a tooltip like this: 

`<div class="missing-photo" v-tooltip.bottom="{ text:myName }">` where `myName` is a string that contains an executable script, like: `<style onload=alert(document.cookie)></style>`.  

Hover over the tooltip and you will see the script execute.

I think the issue is [here](https://github.com/uiv-lib/uiv/blob/1.x/src/components/tooltip/Tooltip.js#L29).  Rather than setting the text to `innerHTML ` we might want to set it to `innerText`.

**Comment by wxsms** [comment]
fixed in 1.4.3

**Comment by sdrioux** [comment]
Super fast, thank you!  When you get a chance if you could publish it to npm that would be great.
