### ISSUE TITLE
Collapse component does not emit event like bootstrap does.

### ISSUE THREAD

**Issue by Tarrask** [wxsms/uiv#81]
The collapse bootstrap component emits events when changing it state:

Event Type | Description
-- | --
show.bs.collapse | This event fires immediately when the show instance method is called.
shown.bs.collapse | This event is fired when a collapse element has been made visible to the user (will wait for CSS transitions to complete).
hide.bs.collapse | This event is fired immediately when the hide method has been called.
hidden.bs.collapse | This event is fired when a collapse element has been hidden from the user (will wait for CSS transitions to complete).

Can we add them to the Collapse uiv component?

The dot notation of the bootstrap event doesn't work well with the v-on directive, but we can rename them `show-collapse`, `shown-collapse` or just `show`, `shown`.

I can make a pull request if interested, but I just want to be sure of the event name to use and that is not something implemented in a different way.

**Comment by wxsms** [comment]
Hi.

Thanks for you suggestion. It's not implemented yet. Pull requests are welcome!
As for the event names, `show` / `shown` / `hide` / `hidden` will be fine, I think.
