### ISSUE TITLE
Newbie needs a working example of Collapse or Modal or Pagination

### ISSUE THREAD

**Issue by mattdunndc** [wxsms/uiv#83]
### Browser and uiv version
Chrome
<script src="//unpkg.com/uiv/dist/uiv.min.js"></script>

### Which component
Got the Tab component working in browser but need a simple working example for Collapase, Pagination, Modal

### Steps to reproduce the problem
Trying to use uiv in the browser without webpack.  Tab Component works great but really need a simple working example of either Collapse/Modal/Pagination.   K

### Actual behavior
Property or method "showCollapse1" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.

**Comment by wxsms** [comment]
Here a collapse example on Codepen: https://codepen.io/wxsm/pen/ZXMPQe
Modal / Pagination are quite the same.

**Comment by mattdunndc** [comment]
Brilliant. Finally got it.  Thank you for taking the time for a codepen.  Really appreciate it.  Awesome work.

**Comment by wxsms** [comment]
Welcome.
