### ISSUE TITLE
Multiselect causing `Uncaught TypeError: this.modelValue is undefined` error

### ISSUE THREAD

**Issue by pdnelson** [wxsms/uiv#831]
**Describe the bug**
When using the Multiselect component, the following error occurs in the console and prevents the page from rendering: `Uncaught TypeError: this.modelValue is undefined`

I am able to get the error to occur with this setup:
```javascript
<multi-select
  v-model="testing"
  :options="['one', 'two', 'three']"
/>
```

Variable `testing` is defined as follows:
```javascript
data() {
  return {
    testing: []
  }
}
```

**To Reproduce**
1. Attempt to load page with above code block
2. Receive console error

**Expected behavior**
Page to load without console error.

**Desktop (please complete the following information):**
- OS: Mac OS Big Sur, v11.2.3
- Browser: Firefox
- Version: 115.0.2

**Additional context**
This is occurring on UIV 2.0.6 with Vue 3.3.4.

**Comment by wxsms** [comment]
```vue
<template>
  <MultiSelect
    v-model="testing"
    :options="[
      { value: 1, label: 'Option1' },
      { value: 2, label: 'Option2' },
      { value: 3, label: 'Option3' },
      { value: 4, label: 'Option4' },
      { value: 5, label: 'Option5' },
    ]"
  />
</template>

<script>
import { MultiSelect } from 'uiv';

export default {
  components: { MultiSelect },
  data() {
    return {
      testing: [],
    };
  },
};
</script>
```

I can not reproduce this issue using the above code (btw options does not support plain texts, you have to use a object with label and value).

Please provide a reproduce link like codepen. thanks.

**Comment by wxsms** [comment]
It fails when using @vue/compat. the `modalValue` pass to component is undefined, which should be an array instead. I have no idea how to make it work.

**Comment by pdnelson** [comment]
I pulled the repository and played around with it for a bit, and experienced the same thing you did; this seems like a problem with @vue/compat, and not UIV. Thank you for looking into it!
