### ISSUE TITLE
Date-picker

### ISSUE THREAD

**Issue by scorpjio** [wxsms/uiv#85]
### Browser and uiv version
chrome 61 
uiv 0.12.0

### Which component
date-picker

### Steps to reproduce the problem
`<dropdown class="form-group col-sm-6">
    <div class="input-group">
        <input class="form-control" type="text" v-model="date" readonly="readonly">
        <span class="input-group-btn" data-role="trigger">
            <button type="button" class="btn btn-primary" style="padding: 8px 4px; border: 1px solid transparent;">
                <i class="glyphicon glyphicon-calendar"></i>
            </button>
        </span>
    </div>
    <template slot="dropdown">
        <li>
            <date-picker id="date-picker" v-model="date" :width="width" :format="format"
                         :limit-from="limitFrom" :week-starts-with="weekStartsWith"></date-picker>
        </li>
    </template>
</dropdown>`

{
            weekStartsWith: 1,
            date: null,
            limitFrom: new Date(),
            format: 'dd/MM/yyyy'
}
### Expected behavior
after selecting date 11 December when open the date picker again December should be open and day 11 should be selected

### Actual behavior
after selecting date 11 December when open the date picker again November is open with day 12 selected

**Comment by wxsms** [comment]
`dd/MM/yyyy` is not supported by `Date.parse`.

> If you need a special format that not supported by `Date.parse`, consider using `date-parser` option to override it.

**Comment by scorpjio** [comment]
Ok, thanks for the quick answer

**Comment by wxsms** [comment]
wlc.

**Comment by wa05** [comment]
@wxsms can you provide an example of using Date.parse thanks

**Comment by wxsms** [comment]
@wa05 just any function, take the same params and return as `Date.parse`

**Comment by wa05** [comment]
I'm not understanding..


<date-picker  :date-parser="setDate(form.initDate)"
                       v-model="form.initDate"/>
....
form.initDate: '14/12/2022',
....
setDate(date) {
        moment(date,'DD-MM-YYYY').toDate()
 }

![image](https://user-images.githubusercontent.com/13040747/37575216-b78b4cac-2b04-11e8-9e79-19d35ca70bfa.png)

**Comment by wxsms** [comment]
@wa05 

```
:date-parser="dateParser"
```

```
dateParser (value) {
  return moment(value, 'DD-MM-YYYY').toDate().getTime()
}
```

**Comment by wxsms** [comment]
sry. maybe I should add this to the document.

**Comment by wa05** [comment]
thanks a lot @wxsms, working now , with the @input event I'm setting the change in the format that I want..

@input="selectedDate"
...

selectedDate( value ){
        this.form.initialDate = moment( value ).format('DD-MM-YYYY')
      },
