### ISSUE TITLE
Reactive recalculating startingSlice

### ISSUE THREAD

**Issue by pixlo** [wxsms/uiv#86]
### Browser and uiv version
Chrome 61. Latest uiv.

### Which component
Pagination

### Steps to reproduce the problem
provide pagination component with v-model, total-page, max-size then asynchronously provide it with different total-page and/or max-size
In my case I am getting max pages asynchronously from API. And binding it to computed property in my component via vuex.

### Expected behavior
To reactively recalculate sliceStart.

### Actual behavior
Recalculating only on value change.

**Comment by wxsms** [comment]
Merged.
