### ISSUE TITLE
Not an issue, new to Vue.js - Need example of Array Pagination

### ISSUE THREAD

**Issue by mattdunndc** [wxsms/uiv#88]
### Browser and uiv version
chrome with //unpkg.com/uiv/dist/uiv.min.js

### Which component
Pagination

### Steps to reproduce the problem
Can run this but how do I page over an Array?

<pagination v-model="currentPage"
                        :boundary-links="boundaryLinks"
                        :direction-links="directionLinks"
                        :total-page="totalSize"
                        :size="size"
                        :max-size="maxSize">
            </pagination>

**Comment by wxsms** [comment]
Hi,

I think you're talking about this: https://codepen.io/wxsm/pen/pdgaOW

**Comment by mattdunndc** [comment]
Yes!  Many thanks for your time and this amazing project.  Really enjoying it!

**Comment by wxsms** [comment]
Welcome.
