### ISSUE TITLE
Add `props` for custom icons

### ISSUE THREAD

**Issue by francoismassart** [wxsms/uiv#89]
### Version & browser
`v0.12.3` & all browsers

### Which components
- DatePicker
  - DateView
  - MonthView
  - YearView
- TimePicker

### Steps to reproduce the problem
The Carousel component provides some `props` for using custom icons: [`icon-control-left`& `icon-control-right`](https://uiv.wxsm.space/carousel#carouselvue) while there is no such `props` available for the Time and Date components.

### Expected behavior
Be able to use custom icons for Date & Time pickers using optional `props`.

### Actual behavior
No `props` available for defining custom icons...

### Proposal
I'd like to add `props` with the current icons values as default. I can take care of the changes in the source code and ake a pull request if you agree.

**Comment by wxsms** [comment]
Merged. Thanks for your contribution!

**Comment by francoismassart** [comment]
You're welcome, I could also add additional tests in the `.spec.js` files for testing usage of custom icons, let me know if you are interested 👍
