### ISSUE TITLE
should Alert close animation

### ISSUE THREAD

**Issue by zcyzcy88** [wxsms/uiv#9]
like collapse

**Comment by wxsms** [comment]
The alert close is not control by the component itself, but its parent using v-if / v-show / v-for. so if you want animation, simply add vue transition to it will do.

**Comment by zcyzcy88** [comment]
Solution:

	<collapse v-model="show">
		<alert type="warning" closable="true" @closed="show = false">
			<strong>Warning!</strong> Better check yourself, you're not looking too good.
		</alert>
	</collapse>

**Comment by wxsms** [comment]
Nice solution. I think this sample shall add to the alert doc.
