### ISSUE TITLE
Using a custom icon breaks the layout of the Carousel component

### ISSUE THREAD

**Issue by francoismassart** [wxsms/uiv#92]
Due to a CSS selector not getting applied:

```
.carousel-control .icon-prev,
.carousel-control .icon-next,
.carousel-control .glyphicon-chevron-left,
.carousel-control .glyphicon-chevron-right
```

PR is coming

**Comment by wxsms** [comment]
Merged.

**Comment by wxsms** [comment]
Hi @francoismassart 

Thanks for reporting this issue and the PR, actually I have never try this prop before.

But you solution is causing all icons become `icon-prev` and `icon-next`, including the default one. I just do some research and refine it. Seems custom CSS may needed in some case. You can check out my commit for details.

**Comment by francoismassart** [comment]
Yes, indeed. Because we cannot edit the official/external CSS file from bootstrap for this issue, here is what I propose as solution: we only concatenate the `icon-prev`and `icon-next` classes to the HTML node of the prev/next if their defined value is different from the default...

This way, if we want to use different/custom icons it is our responsability to edit our custom CSS declarations with just enough specificity to overwrite the specific inherited & unwanted CSS properties coming from the official bootstrap CSS.

Sounds good ?

**Comment by wxsms** [comment]
![image](https://user-images.githubusercontent.com/5960988/32540014-4b31b5e2-c4a6-11e7-8537-7747ae488abe.png)

`icon-prev` / `icon-next` is overriding the font-family, and also the `before` font content. And, it also might not look good while the new icon has more `height`.

While not using them, all we need to add in CSS are:

```
.carousel-control .your-icon {
  top: 50%;
  margin-top: -10px; // half of the new icon height
  position: absolute;
}
```

I think this might be easier. Might also good to have in document.

**Comment by francoismassart** [comment]
I'll make necessary in a PR

**Comment by wxsms** [comment]
Thanks. Just enhance the doc will be enough for now. pls pull latest code first.
